export const ANALYSIS_CARD_COPY = {
  factsLabel: "주요 정보",
  verificationLabel: "대조 결과",
  reportCta: "검증 리포트 보기",
  totalItemsLabel: "대조 항목",
  comparisonTargetLabel: "대조 대상",
  headUnit: "두",
  itemUnit: "건",
  subscriptionLabel: "청약 기간",
  assetLabel: "기초자산",
  minimumInvestmentLabel: "최소 투자금",
  totalOfferingLabel: "총 공모금액",
  acquisitionPriceLabel: "작품 취득가",
  offeringPremiumLabel: "공모가 차이율",
  simulationAmountLabel: "시뮬레이션 금액",
  simulationReturnLabel: "시뮬레이션 수익률",
  holdingPeriodLabel: "보유기간",
  returnedAmountLabel: "반환 기재액",
  soldAmountLabel: "매각 기재액",
  syntheticNotice: "합성 데이터 · 대조 불가",
  syntheticHistoryDescription:
    "화면 검증을 위한 합성 이력이며 실제 투자 실적이 아닙니다.",
  productAnalysisCta: "상품 분석 보기",
  historyDetailCta: "이력 상세 보기",
  recentDisclosurePrefix: "최근 공시",
  asOfPrefix: "기준일",
  syntheticArtworkImageAltSuffix: "합성 작품 이미지",
  catalogTitle: "공모 상품",
} as const;
