import type { AnalysisResult, Artist, CurrentProductView, Evidence, HistoricalOfferingView, Platform, ProductView, TrackRecord } from "@/lib/art/types";

export const syntheticDataMode = "synthetic" as const;

function offeringDto(offering: ProductView["offering"] | HistoricalOfferingView["offering"]) {
  return { id: offering.id, slug: offering.slug, title: offering.title, status: offering.status, subscriptionStart: offering.subscriptionStart, subscriptionEnd: offering.subscriptionEnd, unitPrice: offering.unitPrice, minimumInvestment: offering.minimumInvestment, numberOfUnits: offering.numberOfUnits, totalOfferingAmount: offering.totalOfferingAmount, currency: offering.currency ?? null, currencyNote: offering.currencyNote ?? null, acquisitionPrice: offering.acquisitionPrice, appraisalValue: offering.appraisalValue, targetHoldingMonths: offering.targetHoldingMonths, actualHoldingMonths: offering.actualHoldingMonths, distributionTerms: offering.distributionTerms, exitMethod: offering.exitMethod, midTermTransferAvailable: offering.midTermTransferAvailable, disclosedCosts: offering.disclosedCosts.map((cost) => ({ category: cost.category, label: cost.label, amount: cost.amount })), actualDistributionAmount: offering.actualDistributionAmount, actualExitAmount: offering.actualExitAmount, finalReturn: offering.finalReturn ?? null, soldAt: offering.soldAt ?? null, liquidatedAt: offering.liquidatedAt ?? null, asOfDate: offering.asOfDate, updatedAt: offering.updatedAt, isDemo: true, dataMode: syntheticDataMode, recordScope: offering.recordScope ?? "current", identityStatus: offering.identityStatus ?? "unknown", lifecycle: offering.lifecycle ?? "current" };
}

export function serializeArtist(artist: Artist) { return { id: artist.id, nameKo: artist.nameKo, nameEn: artist.nameEn, birthYear: artist.birthYear, deathYear: artist.deathYear, nationality: artist.nationality, biography: artist.biography, officialCareer: artist.officialCareer.map((career) => ({ type: career.type, title: career.title, year: career.year })), imageUrl: artist.imageUrl?.startsWith("/") ? artist.imageUrl : null, dataMode: syntheticDataMode }; }
export function serializePlatform(platform: Platform) { return { id: platform.id, name: platform.name, operatorName: platform.operatorName, dataMode: syntheticDataMode }; }
export function serializeTrackRecord(record: TrackRecord) { return { productName: record.productName, artworkTitle: record.artworkTitle, artistName: record.artistName, artistNameEn: record.artistNameEn ?? null, artworkProductionYear: record.artworkProductionYear ?? null, artworkMedium: record.artworkMedium ?? null, artworkWidth: record.artworkWidth ?? null, artworkHeight: record.artworkHeight ?? null, artworkDepth: record.artworkDepth ?? null, artworkImageUrl: record.artworkImageUrl?.startsWith("/") ? record.artworkImageUrl : null, subscriptionStart: record.subscriptionStart ?? null, subscriptionEnd: record.subscriptionEnd ?? null, soldPlace: record.soldPlace ?? null, offeringAmount: record.offeringAmount, targetHoldingMonths: record.targetHoldingMonths, actualHoldingMonths: record.actualHoldingMonths, totalDistribution: record.totalDistribution, exitAmount: record.exitAmount, finalReturn: record.finalReturn, status: record.status, delayDays: record.delayDays, soldAt: record.soldAt, liquidatedAt: record.liquidatedAt, currency: record.currency ?? null, currencyNote: record.currencyNote ?? null, exitCurrency: record.exitCurrency ?? null, reportedAmount: record.reportedAmount ?? null, reportedReturn: record.reportedReturn ?? null, sourceReportedReturnPct: record.sourceReportedReturnPct ?? null, calculatedSettlementReturnPct: record.calculatedSettlementReturnPct ?? null, identityStatus: "unknown" as const, lifecycle: record.lifecycle ?? "unknown", dataMode: syntheticDataMode }; }
function evidenceDto(evidence: Evidence) { return { claim: evidence.claim, sourceType: "synthetic", asOfDate: evidence.asOfDate, collectedAt: evidence.collectedAt, formula: evidence.formula, notes: evidence.notes, dataMode: syntheticDataMode }; }
function analysisDto(analysis: AnalysisResult) { const section = (value: AnalysisResult["priceInsight"]) => ({ conclusion: value.conclusion, quantitativeFindings: value.quantitativeFindings, qualitativeFindings: value.qualitativeFindings }); const reason = (value: AnalysisResult["keyReasons"][number]) => ({ title: value.title, finding: value.finding, implication: value.implication }); return { verdict: analysis.verdict, verdictLabel: analysis.verdictLabel, headline: analysis.headline, summary: analysis.summary, keyReasons: analysis.keyReasons.map(reason), priceInsight: section(analysis.priceInsight), artistInsight: section(analysis.artistInsight), exitInsight: section(analysis.exitInsight), platformInsight: section(analysis.platformInsight), missingInformationRisks: analysis.missingInformationRisks, conflicts: analysis.conflicts, updatedAt: analysis.updatedAt, dataMode: syntheticDataMode }; }
function artworkDto(artwork: ProductView["artwork"] | HistoricalOfferingView["artwork"]) { return { id: artwork.id, title: artwork.title, productionYear: artwork.productionYear, medium: artwork.medium, width: artwork.width, height: artwork.height, depth: artwork.depth, edition: artwork.edition, series: artwork.series, provenance: artwork.provenance, condition: artwork.condition, imageUrl: artwork.imageUrl?.startsWith("/") ? artwork.imageUrl : null, dataMode: syntheticDataMode }; }

export function serializeCurrentProduct(product: CurrentProductView | ProductView) { return { recordScope: "current" as const, dataMode: syntheticDataMode, offering: offeringDto(product.offering), artwork: artworkDto(product.artwork), artist: serializeArtist(product.artist), platform: serializePlatform(product.platform), issuer: { legalName: product.issuer.legalName, dataMode: syntheticDataMode }, analysis: analysisDto(product.analysis), auctions: product.auctions.map((auction) => ({ artworkTitle: auction.artworkTitle, auctionDate: auction.auctionDate, auctionHouse: auction.auctionHouse, country: auction.country, productionYear: auction.productionYear, medium: auction.medium, width: auction.width, height: auction.height, depth: auction.depth, edition: auction.edition, series: auction.series, estimateLow: auction.estimateLow, estimateHigh: auction.estimateHigh, hammerPrice: auction.hammerPrice, realizedPrice: auction.realizedPrice, currency: auction.currency, normalizedPriceKRW: auction.normalizedPriceKRW, result: auction.result })), comparables: product.comparables.map((comparable) => ({ sameSeries: comparable.sameSeries, sameMedium: comparable.sameMedium, similarSize: comparable.similarSize, similarYear: comparable.similarYear, similarityScore: comparable.similarityScore, comparisonReason: comparable.comparisonReason, auction: { artworkTitle: comparable.auction.artworkTitle, auctionDate: comparable.auction.auctionDate, normalizedPriceKRW: comparable.auction.normalizedPriceKRW, currency: comparable.auction.currency, result: comparable.auction.result } })), trackRecords: product.trackRecords.map(serializeTrackRecord), evidence: product.evidence.map(evidenceDto), annualMetrics: product.annualMetrics.map((metric) => ({ year: metric.year, offered: metric.offered, sold: metric.sold, medianPrice: metric.medianPrice, unsold: metric.unsold })) }; }
export function serializeHistoricalProduct(product: HistoricalOfferingView) { return { recordScope: "historical" as const, dataMode: syntheticDataMode, offering: offeringDto(product.offering), artwork: artworkDto(product.artwork), artist: serializeArtist(product.artist), platform: serializePlatform(product.platform), trackRecord: serializeTrackRecord(product.trackRecord), identityStatus: "unknown" as const, lifecycle: product.lifecycle }; }
export function serializeCatalogProduct(product: CurrentProductView | HistoricalOfferingView) { return product.recordScope === "historical" ? serializeHistoricalProduct(product) : serializeCurrentProduct(product); }
