import legacyProductsJson from "@/data/products.json";
import artnguideJson from "@/data/artnguide_track_records.json";
import artnguideDueDiligenceJson from "@/data/artnguide_due_diligence.json";
import weshareartJson from "@/data/weshareart_research.json";
import tessaJson from "@/data/tessa_sale_records.json";
import type { AnalysisResult, AnnualAuctionMetric, Artist, Artwork, AuctionRecord, ComparableRecord, Evidence, Issuer, Offering, Platform, TrackRecord, Verdict, VerdictLabel } from "@/lib/art/types";

type LegacySource = { id: string; label: string; as_of: string | null; collected_at?: string | null; url: string; document_name?: string | null; publisher?: string | null };
type LegacyProduct = {
  id: string; category: string; name: string; status: string; status_detail?: string; as_of: string; source_state: string;
  asset: { artist?: string; title?: string; year?: number; material?: string; size?: string };
  art_price?: Record<string, unknown>; artist_market?: Record<string, unknown>; sources: LegacySource[];
  common_model?: Record<string, unknown>;
};
type ArtnguideRecord = { id: number; startAt: string; endAt: string; gpMoney: number | null; soldTime: string | null; soldMoney: number | null; soldPlace: string | null; title: string; authorName: string; yearItem: string; artMaterial: string; artSize: string; status: string; profit: number | null; dateHold: number | null };
type ArtnguideAnnotation = { id: number; page_api_url: string; display?: { status_label?: string; transaction_type?: string } };
type WeshareRecord = { source_urls: { goods_page?: string }; list: { goodsId: number; goodsName: string | null; coPurchaseStatusCategory: string | null; coPurchaseStatus: string | null; investBeginDateTime: string | null; investEndDateTime: string | null; saleYieldPercent: number | null; artistNameForKorean: string | null; titleForKorean: string | null }; detail?: { artwork?: { title?: string; productionYear?: string; material?: string; size1?: number; size2?: number }; quantity?: number; pieceAmount?: number; keepingDays?: number | null } };
type TessaRecord = { record_id: string; disclosure_title: string; disclosure_url: string; page_display_date: string; holding_period_days: number | null; asset: { product_code: string; artist: string; title: string }; initial_price?: { amount_krw?: number; nominal_unit_price_krw?: number }; sale_price?: { amount?: number; currency?: string; final_sale_amount_krw?: number | null }; settlement?: { amount_krw?: number; payout_date?: string }; calculated_settlement_return_pct?: number | null };

type DatasetSummary = { platformId: string; title: string; recordCount: number; asOf: string; mode: string; limitation: string; dueDiligenceRecordCount?: number; identityConfirmedCount?: number; legalIssuerMappingStatus: string; sourceSnapshot?: unknown };

const legacyProducts = (legacyProductsJson as unknown as { products: LegacyProduct[] }).products.filter((product) => product.category === "미술품");
const artnguide = artnguideJson as unknown as { dataset: { title: string; record_count: number; as_of: string; mode: string; legal_issuer_mapping_status: string }; records: ArtnguideRecord[]; record_annotations: ArtnguideAnnotation[] };
const artnguideDue = artnguideDueDiligenceJson as unknown as { coverage: { artist_track_record_count: number; identity_confirmed_record_count: number }; operator_evidence: { operator_name: string; record_level_legal_issuer_mapping_status: string }; limitations: string[]; record_evidence: Array<{ id:number; identity?:{classification?:string;completeness?:string}; external_exact_match?:{status?:string}; same_artist_other_work?:{status?:string} }>; artist_track_records: Array<{ id:number; limitations?:string[] }> };
const weshareart = weshareartJson as unknown as { dataset: { title: string; record_count: number; as_of: string; mode: string }; track_records: { records: WeshareRecord[] }; limitations: string[] };
const tessa = tessaJson as unknown as { dataset: { title: string; record_count: number; as_of: string; mode: string; legal_issuer_mapping_status: string }; records: TessaRecord[]; limitations: string[] };

const verdictLabel: Record<Verdict, VerdictLabel> = { worth_considering: "해볼 만함", conditional: "조건부 해볼 만함", caution: "주의", danger: "위험" };
function numberValue(value: unknown): number | null { return typeof value === "number" && Number.isFinite(value) ? value : null; }
function stringValue(value: unknown): string | null { return typeof value === "string" && value.trim() ? value : null; }
function parseSize(value?: string) { const matches = value?.match(/([\d.]+)\s*[×xX]\s*([\d.]+)/); return { width: matches ? Number(matches[1]) : null, height: matches ? Number(matches[2]) : null }; }
function artistNames(raw?: string) { const value = raw?.trim() || "작가 미확인"; return { ko: value, en: null }; }
function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9가-힣]+/g, "-").replace(/^-|-$/g, ""); }
function isoDate(value: string | null | undefined) { return value ? value.slice(0, 10) : null; }

export const legacyPlatforms: Platform[] = [
  { id: "platform-togetherart", name: "투게더아트", operatorName: "주식회사 투게더아트", website: "https://weshareart.com", issuerIds: ["issuer-togetherart"], sourceIds: [] },
  { id: "platform-arttogether", name: "아트투게더", operatorName: "레코드별 운영·발행 주체 미확인", website: "https://weshareart.com", issuerIds: [], sourceIds: ["legacy-platform-arttogether-dataset"] },
  { id: "platform-artnguide", name: "아트앤가이드", operatorName: `${artnguideDue.operator_evidence.operator_name} (플랫폼 자체 기재·미검증)`, website: "https://artnguide.co.kr", issuerIds: ["issuer-artnguide-unverified"], sourceIds: ["legacy-platform-artnguide-dataset", "legacy-artnguide-due-diligence"] },
  { id: "platform-tessa", name: "TESSA", operatorName: "운영사 원문 대조 필요", website: "http://www.tessa.art", issuerIds: ["issuer-tessa-unverified"], sourceIds: ["legacy-platform-tessa-dataset"] },
];
export const legacyIssuers: Issuer[] = [
  { id: "issuer-togetherart", legalName: "주식회사 투게더아트", registrationNumber: null, platformIds: ["platform-togetherart"], sourceIds: [] },
  { id: "issuer-artnguide-unverified", legalName: "레코드별 법적 발행사 미확인", registrationNumber: null, platformIds: ["platform-artnguide"], sourceIds: ["legacy-artnguide-due-diligence"] },
  { id: "issuer-tessa-unverified", legalName: "레코드별 법적 발행사 미확인", registrationNumber: null, platformIds: ["platform-tessa"], sourceIds: ["legacy-platform-tessa-dataset"] },
];

export const legacyDatasetSummaries: DatasetSummary[] = [
  { platformId: "platform-artnguide", title: artnguide.dataset.title, recordCount: artnguide.records.length, asOf: artnguide.dataset.as_of, mode: artnguide.dataset.mode, limitation: "플랫폼 자체 게시 이력이며 매각·입금·정산을 독립 검증하지 않았습니다.", dueDiligenceRecordCount: artnguideDue.coverage.artist_track_record_count, identityConfirmedCount: artnguideDue.coverage.identity_confirmed_record_count, legalIssuerMappingStatus: artnguide.dataset.legal_issuer_mapping_status, sourceSnapshot: artnguideDueDiligenceJson },
  { platformId: "platform-arttogether", title: weshareart.dataset.title, recordCount: weshareart.track_records.records.length, asOf: weshareart.dataset.as_of, mode: weshareart.dataset.mode, limitation: "플랫폼 자체 게시 공동구매 기록이며 인증이 필요한 매각 상세는 확인하지 않았습니다.", legalIssuerMappingStatus: "unverified_no_auto_merge", sourceSnapshot: weshareartJson },
  { platformId: "platform-tessa", title: tessa.dataset.title, recordCount: tessa.records.length, asOf: tessa.dataset.as_of, mode: tessa.dataset.mode, limitation: "플랫폼 자체 정산 공시이며 매매계약·입금 자료를 독립 검증하지 않았습니다.", legalIssuerMappingStatus: tessa.dataset.legal_issuer_mapping_status, sourceSnapshot: tessaJson },
];

export const legacyPlatformEvidence: Evidence[] = legacyDatasetSummaries.flatMap((summary) => {
  const base: Evidence = { id: `legacy-${summary.platformId}-dataset`, entityType: "Platform", entityId: summary.platformId, fieldPath: "trackRecords", claim: `${summary.title} 연결`, value: { recordCount: summary.recordCount, mode: summary.mode, legalIssuerMappingStatus: summary.legalIssuerMappingStatus }, sourceTitle: summary.title, sourcePublisher: summary.platformId === "platform-artnguide" ? "아트앤가이드" : summary.platformId === "platform-arttogether" ? "아트투게더" : "TESSA", sourceUrl: summary.platformId === "platform-artnguide" ? "https://artnguide.co.kr/purchase-summary" : summary.platformId === "platform-arttogether" ? "https://weshareart.com/goods?type=ALL&page=1" : "http://www.tessa.art/공시", sourceType: "verified_snapshot_self_reported", asOfDate: summary.asOf.slice(0, 10), collectedAt: summary.asOf, formula: null, notes: summary.limitation };
  if (summary.platformId !== "platform-artnguide") return [base];
  return [base, { ...base, id: "legacy-artnguide-due-diligence", fieldPath: "dueDiligence", claim: "아트앤가이드 로컬 실사 데이터 연결", value: { trackRecords: summary.dueDiligenceRecordCount, identityConfirmed: summary.identityConfirmedCount, legalIssuerMappingStatus: artnguideDue.operator_evidence.record_level_legal_issuer_mapping_status }, sourceTitle: "아트앤가이드 due-diligence 저장본", sourcePublisher: "DAKER 로컬 검증", sourceUrl: null, sourceType: "local_due_diligence", notes: "작가명 정규화와 레코드 Evidence를 연결했으나 레코드별 법적 발행사는 확인되지 않았습니다." }];
});

export const legacyTrackRecords: TrackRecord[] = [
  ...artnguide.records.map((record): TrackRecord => { const annotation = artnguide.record_annotations.find((item) => item.id === record.id); const dueEvidence=artnguideDue.record_evidence.find((item)=>item.id===record.id); const dueTrack=artnguideDue.artist_track_records.find((item)=>item.id===record.id); const status: TrackRecord["status"] = record.status === "TRANSFER" ? "sold" : record.status === "EXPECTED_TRANSFER" ? "exit_in_progress" : "sold"; return { id: `artnguide-${record.id}`, platformId: "platform-artnguide", issuerId: null, offeringId: null, productName: `${record.authorName} 〈${record.title}〉`, artworkTitle: record.title, artistName: record.authorName, offeringAmount: record.gpMoney, targetHoldingMonths: null, actualHoldingMonths: record.dateHold == null ? null : record.dateHold / 30.4375, totalDistribution: null, exitAmount: record.status === "EXPECTED_TRANSFER" ? null : record.soldMoney, finalReturn: null, status, delayDays: null, soldAt: isoDate(record.soldTime), liquidatedAt: null, sourceIds: ["legacy-platform-artnguide-dataset"], rawStatus: `${record.status}${annotation?.display?.status_label ? ` · ${annotation.display.status_label}` : ""}`, sourceLabel: annotation?.display?.transaction_type || "플랫폼 게시 기록", sourceUrl: annotation?.page_api_url || "https://artnguide.co.kr/purchase-summary", isSelfReported: true, currencyNote: "원화로 게시된 플랫폼 원값", evidenceNote: dueTrack?.limitations?.join(" · ")??null, identityStatus: dueEvidence?`${dueEvidence.identity?.classification??"미확인"} / ${dueEvidence.identity?.completeness??"미확인"} / exact ${dueEvidence.external_exact_match?.status??"미확인"}`:null, legalIssuerStatus: artnguideDue.operator_evidence.record_level_legal_issuer_mapping_status, reportedReturn: record.profit, legacySourceRef: `artnguide:${record.id}`, sourcePayload:{record,annotation}, dueDiligencePayload:{recordEvidence:dueEvidence??null,artistTrackRecord:dueTrack??null} }; }),
  ...weshareart.track_records.records.map((record): TrackRecord => { const detail = record.detail; const quantity = numberValue(detail?.quantity); const pieceAmount = numberValue(detail?.pieceAmount); const amount = quantity != null && pieceAmount != null ? quantity * pieceAmount : null; const distributed = record.list.coPurchaseStatusCategory === "DISTRIBUTED"; return { id: `weshareart-${record.list.goodsId}`, platformId: "platform-arttogether", issuerId: null, offeringId: null, productName: record.list.goodsName || `아트투게더 상품 ${record.list.goodsId}`, artworkTitle: record.list.titleForKorean || detail?.artwork?.title || record.list.goodsName || "작품명 미기재", artistName: record.list.artistNameForKorean || "작가 미기재", offeringAmount: null, targetHoldingMonths: null, actualHoldingMonths: numberValue(detail?.keepingDays) == null ? null : (numberValue(detail?.keepingDays) as number) / 30.4375, totalDistribution: null, exitAmount: null, finalReturn: distributed ? record.list.saleYieldPercent : null, status: distributed ? "liquidated" : "operating", delayDays: null, soldAt: null, liquidatedAt: null, sourceIds: ["legacy-platform-arttogether-dataset"], rawStatus: `${record.list.coPurchaseStatusCategory ?? "-"} / ${record.list.coPurchaseStatus ?? "-"}`, sourceLabel: "아트투게더 자체 게시 공동구매", sourceUrl: record.source_urls.goods_page || null, isSelfReported: true, currencyNote: "통화 코드 미기재: 원화로 표시하지 않음", reportedAmount: amount, legacySourceRef: `weshareart:goods:${record.list.goodsId}`, sourcePayload:record }; }),
  ...tessa.records.map((record): TrackRecord => { const saleKrw = record.sale_price?.currency === "KRW" ? numberValue(record.sale_price.amount) : numberValue(record.sale_price?.final_sale_amount_krw); return { id: record.record_id, platformId: "platform-tessa", issuerId: null, offeringId: null, productName: `${record.asset.product_code} ${record.asset.artist} 〈${record.asset.title}〉`, artworkTitle: record.asset.title, artistName: record.asset.artist, offeringAmount: numberValue(record.initial_price?.amount_krw), targetHoldingMonths: null, actualHoldingMonths: record.holding_period_days == null ? null : record.holding_period_days / 30.4375, totalDistribution: numberValue(record.settlement?.amount_krw), exitAmount: saleKrw, finalReturn: numberValue(record.calculated_settlement_return_pct), status: (numberValue(record.calculated_settlement_return_pct)??0)<0 ? "loss_confirmed" : "liquidated", delayDays: null, soldAt: null, liquidatedAt: record.settlement?.payout_date || record.page_display_date, sourceIds: ["legacy-platform-tessa-dataset"], rawStatus: "매각대금 정산 및 지급 공시", sourceLabel: "TESSA 자체 공시", sourceUrl: record.disclosure_url, isSelfReported: true, currencyNote: record.sale_price?.currency && record.sale_price.currency !== "KRW" ? `${record.sale_price.currency} 거래: 원화 환산 매각가가 명시된 경우에만 exitAmount 사용` : "KRW", evidenceNote:"플랫폼 자체 공시 계산값이며 비연환산·개인 세전·원 미만 단위 한계를 유지합니다.", legacySourceRef: `tessa:${record.record_id}`, sourcePayload:record }; }),
];

const offerings: Offering[] = [];
const artworks: Artwork[] = [];
const artists: Artist[] = [];
const auctions: AuctionRecord[] = [];
const comparables: ComparableRecord[] = [];
const evidence: Evidence[] = [];
const analyses: AnalysisResult[] = [];
const annualMetrics: Record<string, AnnualAuctionMetric[]> = {};

legacyProducts.forEach((product) => {
  const names = artistNames(product.asset.artist); const artistId = `legacy-artist-${slug(product.id)}`; const artworkId = `legacy-artwork-${slug(product.id)}`; const size = parseSize(product.asset.size); const artPrice = product.art_price || {}; const market = product.artist_market || {}; const sourceIds = product.sources.map((source) => `legacy-source-${product.id}-${source.id}`); const factsEvidenceId=`legacy-facts-${product.id}`; sourceIds.push(factsEvidenceId);
  const acquisition = numberValue(artPrice.acquisition); const total = numberValue(artPrice.offering); const issuanceCost = numberValue(artPrice.issuance_cost); const disclosedCosts = issuanceCost == null ? [] : [{ category: "issuance", label: "발행비용", amount: issuanceCost }];
  offerings.push({ id: product.id, slug: product.id, artworkId, artistId, platformId: "platform-togetherart", issuerId: "issuer-togetherart", title: product.name, status: "unverified", subscriptionStart: null, subscriptionEnd: null, unitPrice: numberValue(artPrice.unit_price), minimumInvestment: numberValue(artPrice.unit_price), numberOfUnits: numberValue(artPrice.units), totalOfferingAmount: total, acquisitionPrice: acquisition, appraisalValue: null, targetHoldingMonths: null, actualHoldingMonths: null, distributionTerms: null, exitMethod: null, midTermTransferAvailable: null, disclosedCosts, actualDistributionAmount: null, actualExitAmount: null, asOfDate: product.as_of, updatedAt: null, sourceIds, isDemo: false });
  artworks.push({ id: artworkId, artistId, title: product.asset.title || product.name, productionYear: product.asset.year ?? null, medium: product.asset.material || null, width: size.width, height: size.height, depth: null, edition: null, series: stringValue(artPrice.series), provenance: null, condition: null, imageUrl: "/art-placeholder.svg", sourceIds });
  artists.push({ id: artistId, nameKo: names.ko, nameEn: names.en, birthYear: null, deathYear: null, nationality: null, biography: null, officialCareer: [], imageUrl: "/art-placeholder.svg", sourceIds });
  product.sources.forEach((source) => evidence.push({ id: `legacy-source-${product.id}-${source.id}`, entityType: "Offering", entityId: product.id, fieldPath: "source", claim: source.label, value: { productStatus: product.status, sourceState: product.source_state }, sourceTitle: source.document_name || source.label, sourcePublisher: source.publisher || "publisher 미기재", sourceUrl: source.url, sourceType: source.label, asOfDate: source.as_of, collectedAt: source.collected_at??null, formula: null, notes: product.status_detail || product.status }));
  evidence.push({ id:factsEvidenceId, entityType:"Offering", entityId:product.id, fieldPath:"legacyStructuredFacts", claim:"기존 상품 DB 원값 연결", value:{product}, sourceTitle:"기존 products.json 구조화 저장본", sourcePublisher:"원문별 publisher 미기재", sourceUrl:product.sources[0]?.url??null, sourceType:"legacy_structured_snapshot", asOfDate:product.as_of, collectedAt:null, formula:null, notes:"가격 기재값·작가 집계·원문 상태를 보존하며 결측값을 추정하지 않습니다." });
  const lots = numberValue(market.lots); const sold = numberValue(market.sold); const year = numberValue(market.year) ?? numberValue(market.period); if (lots != null && sold != null && year != null) annualMetrics[artistId] = [{ year, offered: lots, sold, unsold: Math.max(0, lots - sold), medianPrice: null }]; else annualMetrics[artistId] = [];
  const comparableValues = Array.isArray(market.comparables) ? market.comparables as Array<Record<string, unknown>> : [];
  if (market.different_work && typeof market.different_work === "object") comparableValues.push(market.different_work as Record<string, unknown>);
  if (numberValue(artPrice.hammer) != null) comparableValues.push({ work: product.asset.title, date: artPrice.hammer_date, venue: "KYS 보고", amount: artPrice.hammer, currency: "KRW", exactReported: true });
  comparableValues.forEach((item, comparableIndex) => { const auctionId = `legacy-auction-${product.id}-${comparableIndex + 1}`; const currency = stringValue(item.currency) || "KRW"; const amount = numberValue(item.amount); const isVerifiedHammer=Boolean(item.exactReported); const auction: AuctionRecord = { id: auctionId, artistId, artworkTitle: stringValue(item.work) || "작품명 미기재", auctionDate: stringValue(item.date) || product.as_of, auctionHouse: stringValue(item.venue) || "경매사 미기재", country: null, lotNumber: null, productionYear: null, medium: null, width: parseSize(stringValue(item.size) || undefined).width, height: parseSize(stringValue(item.size) || undefined).height, depth: null, edition: null, series: null, estimateLow: null, estimateHigh: null, hammerPrice: isVerifiedHammer?amount:null, realizedPrice: isVerifiedHammer?amount:null, currency, normalizedPriceKRW: isVerifiedHammer&&currency === "KRW" ? amount : null, result: isVerifiedHammer&&amount!=null ? "sold" : "unknown", reportedPrice: amount, priceBasis: stringValue(item.venue), verificationStatus: isVerifiedHammer?"issuer_reported_hammer_identity_unverified":"reported_price_basis_unverified", sourceIds }; auctions.push(auction); comparables.push({ id: `legacy-comparable-${product.id}-${comparableIndex + 1}`, offeringId: product.id, auctionRecordId: auctionId, sameSeries: Boolean(item.exactReported), sameMedium: false, similarSize: Boolean(item.size), similarYear: false, similarityScore: item.exactReported ? 0.65 : 0.5, comparisonReason: item.exactReported ? "동일 작품으로 보고됐으나 provenance·lot 식별은 미확인" : "기존 원문에 기재된 동일 작가 비교 작품" }); });
  const sellThrough = numberValue(market.sell_through_pct); const unexplained = total != null && acquisition != null ? total - acquisition - (issuanceCost ?? 0) : null; let verdict: Verdict; let headline: string; if (acquisition == null) { verdict = "danger"; headline = "실제 취득가 또는 독립 비교자료가 부족해 공모가격을 검증하기 어렵습니다."; } else if (comparableValues.length === 0) { verdict = "danger"; headline = "취득가와 공모금액 연결은 확인되지만 독립 비교거래와 현재 회수 상태가 부족합니다."; } else { verdict = sellThrough != null && sellThrough >= 70 && unexplained === 0 ? "conditional" : "caution"; headline = unexplained === 0 ? "공모가격 구성은 설명되지만 현재 회수 상태와 비교 표본의 한계가 남습니다." : "공모가격 차이와 작품 식별·회수 불확실성을 함께 주의해야 합니다."; }
  const platformEvidenceId = "legacy-platform-arttogether-dataset"; const priceFinding = acquisition == null ? "작품 취득가 비공개" : `취득가 ${acquisition.toLocaleString("ko-KR")}원, 공모금액 ${total?.toLocaleString("ko-KR") ?? "비공개"}원${unexplained == null ? "" : `, 미설명 차액 ${unexplained.toLocaleString("ko-KR")}원`}`; const artistFinding = sellThrough == null ? `독립 경매 집계 부족, 연결 비교작 ${comparableValues.length}건` : `원문 집계 출품 ${lots ?? "-"}건, 낙찰 ${sold ?? "-"}건, 낙찰률 ${sellThrough.toFixed(1)}%`;
  const summary = `${priceFinding}. ${artistFinding}. 현재 상품의 청약·처분 가능 상태와 목표 보유기간은 공개 저장본에서 확인되지 않았습니다. 동일 호스트에서 수집한 별도 아트투게더 과거 공동구매 ${weshareart.track_records.records.length}건은 플랫폼 자체 게시 자료이며 레코드별 매각·정산을 독립 검증하지 않았습니다. 자료 부족을 가격·회수 위험에 반영해 ${verdictLabel[verdict]}으로 판단했습니다.`;
  const section = (conclusion: string, quantitativeFindings: string[], qualitativeFindings: string[], ids: string[]) => ({ conclusion, quantitativeFindings, qualitativeFindings, evidenceIds: ids });
  analyses.push({ offeringId: product.id, methodologyVersion: "art-mvp-v1.0", verdict, verdictLabel: verdictLabel[verdict], headline, summary, keyReasons: [{ title: "공모가격 구조", finding: priceFinding, implication: acquisition == null ? "가격 검증의 핵심 기준이 없어 위험에 반영했습니다." : "공개된 금액 연결과 남는 차액을 구분했습니다.", evidenceIds: sourceIds }, { title: "작가 시장", finding: artistFinding, implication: "작가 전체 집계와 현재 작품에 직접 연결된 비교 표본을 구분해야 합니다.", evidenceIds: sourceIds }, { title: "회수·플랫폼 이력", finding: `아트투게더 자체 게시 공동구매 ${weshareart.track_records.records.length}건 연결`, implication: "명칭과 법적 관계를 확정하지 않아 투게더아트 상품의 발행사별 청산 실적으로 자동 합산하지 않았습니다.", evidenceIds: [platformEvidenceId] }], priceInsight: section(acquisition == null ? "취득가가 없어 감정가로 대체하지 않고 위험으로 반영했습니다." : "공개 금액과 비용으로 공모가격 구성을 계산했습니다.", [priceFinding], [stringValue(artPrice.warning) || "원문 한계를 함께 반영했습니다."], sourceIds), artistInsight: section("작가 전체 경매 집계와 현재 작품 비교 표본을 분리했습니다.", [artistFinding], ["USD 거래는 환율 기준이 없어 KRW 중위값에 합산하지 않았습니다."], sourceIds), exitInsight: section("현재 청약·처분 상태와 목표기간 자료가 부족해 회수 시점을 보수적으로 봐야 합니다.", [product.status, product.as_of], [product.status_detail || "현재 상태 재확인이 필요합니다."], sourceIds), platformInsight: section("플랫폼 자체 게시 이력은 연결했지만 발행사별 청산 완료로 자동 합산하지 않았습니다.", [`아트투게더 별도 저장본 ${weshareart.track_records.records.length}건`], ["투게더아트 상품과 아트투게더 이력은 명칭·법적 관계를 확정하지 않아 자동 합산하지 않았습니다."], [platformEvidenceId]), missingInformationRisks: [acquisition == null ? "작품 취득가 비공개" : null, comparableValues.length === 0 ? "독립 비교거래 부족" : null, "현재 청약·처분 가능 상태 미확인", "목표 보유기간 미확인"].filter((value): value is string => Boolean(value)), conflicts: [], evidenceIds: [...sourceIds, platformEvidenceId], updatedAt: product.as_of });
});

export const legacyArtData = { offerings, artworks, artists, auctions, comparables, evidence: [...evidence, ...legacyPlatformEvidence], analyses, annualMetrics };
