import assert from "node:assert/strict";
import fs from "node:fs";import {artComparableStats,artEvidenceAssessment,artEvidenceVerdict,artShares,broadGapMessage,broadStats,evidenceConfidence,lifecycleState,percent,priceBurden,pricing,realEstateComparison,recoveryRisk,searchProducts,selectionAfterSearch,sourceExpired} from "../js/calculations.js";
const fixedNow=new Date("2026-08-08T00:00:00+09:00");
assert.equal(sourceExpired("2020-01-01",fixedNow),true);assert.equal(sourceExpired("2026-08-08",fixedNow),false);
assert.equal(sourceExpired("2026-02-09",fixedNow),false);assert.equal(sourceExpired("2026-02-08",fixedNow),true);assert.equal(sourceExpired("2026-08-08garbage",fixedNow),null);assert.equal(sourceExpired("2026-08-08T15:00:00Z","2026-08-09"),false);
assert.equal(sourceExpired("2026-02-30T00:00:00+09:00",fixedNow),null);
const rows=n=>Array.from({length:n},(_,i)=>({land_per_m2:100+i,gross_per_m2:100+i}));
for(const [n,s] of [[4,"보류"],[5,"낮음"],[9,"낮음"],[10,"중간"]])assert.equal(realEstateComparison({real_estate:{strict_comps:rows(n),offering_units:{land_per_m2:100,gross_per_m2:100}}}).strength,s);
assert.equal(realEstateComparison({real_estate:{strict_comps:[],offering_units:{}}}).verdict,"자료 부족·가격 적정성 판정 보류");
assert.equal(realEstateComparison({real_estate:{strict_comps:rows(5),offering_units:{}}}).code,"INSUFFICIENT");
assert.equal(priceBurden({category:"부동산",real_estate:{strict_comps:rows(5),offering_units:{}}}).value,"판정 보류");
const invalidRows=rows(5);invalidRows[0].gross_per_m2=0;assert.equal(realEstateComparison({real_estate:{strict_comps:invalidRows,offering_units:{land_per_m2:100,gross_per_m2:100}}}).code,"INSUFFICIENT");
assert.equal(artEvidenceVerdict({as_of:"2026-08-08",art_price:{acquisition:1,issuance_cost:1,offering:2},artist_market:{sell_through_pct:1}}),"비용 연결 확인 · 가격 적정성은 별도 확인 필요");
const a={acquisition:203760000,issuance_cost:21240000,offering:225000000,public_subscription:116000000,planned_public_allocation:202500000,issuer_take_up:109000000}, q=artShares(a);assert.equal(q.cost_reconciled,true);assert.equal((q.public_of_offering*100).toFixed(2),"51.56");assert.equal((q.public_of_planned*100).toFixed(2),"57.28");
const ps=[{id:"a",name:"alpha"},{id:"b",name:"beta"}];assert.equal(selectionAfterSearch(ps,"beta",ps[0]).id,"b");assert.equal(selectionAfterSearch(ps,"none",ps[0]),null);
const products=JSON.parse(fs.readFileSync(new URL('../data/products.json',import.meta.url))).products;assert.equal(searchProducts(products,"야요이 쿠사마")[0].id,"at-kusama-001");assert.equal(searchProducts(products,"조지 콘도")[0].id,"at-condo-002");assert.equal(searchProducts(products,"화서문로 76-3")[0].id,"sou-product-7");assert.equal(searchProducts(products,"20240325000139")[0].id,"at-condo-002");assert.equal(selectionAfterSearch(products,"없는 상품",products[0]),null);
assert.equal(artEvidenceVerdict(products.find(x=>x.id==="at-kusama-001")),"독립 비교자료 부족 · 가격 적정성 판정 보류");
assert.equal(lifecycleState({category:"부동산",status:"거래 중단 / 운용 중",status_code:"TRADING_STOPPED"}),"OPERATING");
assert.equal(lifecycleState({category:"부동산",status:"매각 완료",sale_list_check:{listed:false}}),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"부동산",status:"매각 완료",sale_list_check:{listed:true}}),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2026-08-08",source_url:"https://example.test/sold"}},fixedNow),"COMPLETED");
assert.equal(lifecycleState({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2026-08-08T23:59:59+09:00",source_url:"https://example.test/sold"}},fixedNow),"OUTSIDE_FILTER");
assert.notEqual(recoveryRisk({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2026-08-08T23:59:59+09:00",source_url:"https://example.test/sold"}},fixedNow).value,"회수 완료 확인");
assert.equal(lifecycleState({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2026-08-08T00:00:00+09:00",source_url:"https://example.test/sold"}},new Date("2026-08-08T12:00:00+09:00")),"COMPLETED");
assert.equal(lifecycleState({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2099-01-01",source_url:"https://example.test/sold"}},fixedNow),"OUTSIDE_FILTER");
assert.notEqual(recoveryRisk({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2099-01-01",source_url:"https://example.test/sold"}},fixedNow).value,"회수 완료 확인");
assert.equal(lifecycleState({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2026-02-30T00:00:00+09:00",source_url:"https://example.test/sold"}},fixedNow),"OUTSIDE_FILTER");
assert.notEqual(recoveryRisk({category:"부동산",as_of:"2026-08-08",status:"매각 완료",sale_list_check:{listed:true,checked_at:"2026-02-30T00:00:00+09:00",source_url:"https://example.test/sold"}},fixedNow).value,"회수 완료 확인");
assert.equal(lifecycleState({category:"부동산",as_of:"2026-08-08",status:"매각 완료 / 현재 상태 재확인 필요",sale_list_check:{listed:true,checked_at:"2026-08-08",source_url:"https://example.test/sold"}},fixedNow),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"미술품",status:"처분 완료"}),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2026-08-08",source_url:"https://example.test/disposal"}},fixedNow),"COMPLETED");
assert.equal(lifecycleState({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2026-08-08T23:59:59+09:00",source_url:"https://example.test/disposal"}},fixedNow),"OUTSIDE_FILTER");
assert.notEqual(recoveryRisk({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2026-08-08T23:59:59+09:00",source_url:"https://example.test/disposal"}},fixedNow).value,"회수 완료 확인");
assert.equal(lifecycleState({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2026-08-08T00:00:00+09:00",source_url:"https://example.test/disposal"}},new Date("2026-08-08T12:00:00+09:00")),"COMPLETED");
assert.equal(lifecycleState({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2099-01-01",source_url:"https://example.test/disposal"}},fixedNow),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2026-02-30T00:00:00+09:00",source_url:"https://example.test/disposal"}},fixedNow),"OUTSIDE_FILTER");
assert.notEqual(recoveryRisk({category:"미술품",as_of:"2026-08-08",status:"처분 완료",completion_check:{confirmed:true,checked_at:"2026-02-30T00:00:00+09:00",source_url:"https://example.test/disposal"}},fixedNow).value,"회수 완료 확인");
assert.equal(lifecycleState({category:"미술품",status:"처분 완료 · 처분 공시 미발견"}),"OUTSIDE_FILTER");
assert.equal(lifecycleState(products.find(x=>x.id==="sou-product-13")),"OPERATING");
assert.equal(lifecycleState(products.find(x=>x.id==="sou-product-6")),"OUTSIDE_FILTER");
assert.equal(lifecycleState(products.find(x=>x.id==="sou-product-7")),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"부동산",status:"매각 완료",status_detail:"현재 상태 재확인 필요",sale_list_check:{listed:true}}),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"미술품",status:"발행 완료"}),"OUTSIDE_FILTER");
assert.equal(lifecycleState({category:"미술품",status:"처분 완료",status_detail:"처분 공시 미발견"}),"OUTSIDE_FILTER");
assert.deepEqual(pricing({category:"부동산",offering:{amount:100,entrusted_benefit_payment:90}}),{offering:100,base:null,premium:null,base_field:"offering.acquisition"});
assert.equal(pricing({category:"미술품",art_price:{offering:120,acquisition:100}}).premium.toFixed(2),"0.20");
assert.equal(percent(.24375),"24.38%");
assert.equal(percent(-.24375),"-24.38%");
assert.equal(percent(pricing(products.find(x=>x.id==="sou-product-13")).premium),"24.38%");
assert.equal(recoveryRisk({status_code:"TRADING_STOPPED",status:"운용 중"}).value,"회수 경로 제한");
assert.equal(recoveryRisk({status:"처분 공시 미발견"}).value,"확인 필요");
assert.equal(recoveryRisk({status:"운용 중",status_detail:"현재 상태 재확인 필요."}).value,"확인 필요");
assert.equal(evidenceConfidence({category:"미술품",as_of:"2026-08-08",sources:[{as_of:"2026-08-08",label:"원문",url:"https://example.test"}],art_price:{independent_comparables:"insufficient"}},fixedNow).value,"제한적");
assert.equal(evidenceConfidence({category:"부동산",as_of:"2026-08-08",sources:[{as_of:"2025-01-01",label:"원문",url:"https://example.test"}],real_estate:{strict_comps:[]}},fixedNow).value,"현재성 확인 필요");
assert.equal(evidenceConfidence({category:"부동산",as_of:"2026-08-08",sources:[{}],real_estate:{strict_comps:[]}},fixedNow).value,"확인 불가");
assert.deepEqual(evidenceConfidence({category:"미술품",as_of:"2026-08-08",sources:[{as_of:"2026-08-08",url:"https://example.test"}]},fixedNow),{value:"확인 불가",reason:"원문 출처 이름 없음"});
assert.deepEqual(evidenceConfidence({category:"미술품",as_of:"2026-08-08",sources:[{as_of:"2026-08-08",label:"원문",url:"file:///tmp/x"}]},fixedNow),{value:"확인 불가",reason:"원문 출처 URL 확인 불가"});
assert.deepEqual(evidenceConfidence({category:"부동산",as_of:"2026-08-08",sources:[],real_estate:{strict_comps:[]}},fixedNow),{value:"확인 불가",reason:"원문 출처 없음"});
assert.deepEqual(evidenceConfidence({category:"부동산",as_of:"2025-01-01",sources:[{as_of:"2025-01-01",label:"원문",url:"https://example.test"}],real_estate:{strict_comps:[]}},fixedNow),{value:"현재성 확인 필요",reason:"현재 조회일 대비 상품 기준일 180일 초과"});
assert.deepEqual(evidenceConfidence({category:"부동산",as_of:"2026-08-08",sources:[{as_of:"2026-08-08",label:"원문",url:"https://example.test"}],real_estate:{strict_comps:rows(5),offering_units:{}}},fixedNow),{value:"제한적",reason:"엄격 비교 근거가 가격 판정에 충분하지 않음"});
assert.equal(priceBurden({category:"부동산",real_estate:{strict_comps:[],offering_units:{}}}).value,"판정 보류");
assert.equal(priceBurden({category:"미술품",as_of:"2026-08-08",art_price:{exact_work_evidence:{reported:true,row_url:"https://example.test",identity_confidence:"중간"}}}).value,"가격 주의");
assert.equal(evidenceConfidence({category:"미술품",as_of:"2026-08-08",sources:[{as_of:"2026-08-08",label:"원문",url:"https://example.test"}],art_price:{exact_work_evidence:{identity_confidence:"높음"}}},fixedNow).value,"제한적");
assert.equal(evidenceConfidence({category:"미술품",as_of:"2026-08-08",sources:[{as_of:"2026-08-08",label:"원문",url:"https://example.test"}],art_price:{exact_work_evidence:{reported:true,row_url:"https://example.test/row",identity_confidence:"높음"}}},fixedNow).value,"보통");
assert.equal(priceBurden({category:"부동산",real_estate:{strict_comps:rows(5),offering_units:{land_per_m2:100,gross_per_m2:100}}}).value,"비교 범위");
assert.equal(artEvidenceAssessment({category:"미술품",art_price:{}}).code,"UNKNOWN");
assert.equal(artEvidenceVerdict({category:"미술품",art_price:{}}),"확인 불가");
const snap=JSON.parse(fs.readFileSync(new URL('../data/source_snapshots.json',import.meta.url))).rtms_daejeon_gungdong.rows,stats=broadStats(snap);assert.equal(Math.round(stats.land_per_m2),5404045);assert.equal(Math.round(stats.gross_per_m2),1984418);
assert.match(broadGapMessage({offering_units:{land_per_m2:4797493,gross_per_m2:3076115}},snap).message,/엇갈립니다/);
assert.deepEqual(broadGapMessage({offering_units:{land_per_m2:null,gross_per_m2:3076115}},snap),{land:null,gross:null,message:"비교 단가 확인 불가"});
const comparable=artComparableStats({art_price:{offering:225,acquisition:203.76},artist_market:{comparables:[{currency:"KRW",amount:279.6},{currency:"KRW",amount:279.6},{currency:"KRW",amount:262.125},{currency:"USD",amount:10}]}});assert.equal(comparable.count,3);assert.equal(comparable.median,279.6);assert.equal((comparable.offering_gap*100).toFixed(2),"-19.53");
assert.equal(artComparableStats({artist_market:{}}).available,false);assert.equal(artComparableStats({artist_market:{comparables:[]}}).available,true);assert.equal(artShares({offering:100}).cost_reconciled,null);
console.log("PASS: calculations");
