import Image from "next/image";
import Link from "next/link";
import { formatKrw, formatPercent } from "@/lib/domain/calculations";
import { resolvedTrackReturn } from "@/lib/art/track-return";
import type { HistoricalOfferingView, TrackRecord, TrackStatus } from "@/lib/art/types";
import { Breadcrumb, MetricCard, PageContainer } from "@/components/art/ui";

const trackStatusLabels: Record<TrackStatus, string> = { offering: "청약", operating: "운용 중", exit_in_progress: "매각 진행", sold: "매각 완료", returned: "반환", liquidated: "청산 완료", delayed: "지연 청산", unsold: "미매각", loss_confirmed: "손실 확인", unknown: "상태 미확인" };
export function trackStatusLabel(record: TrackRecord) { return trackStatusLabels[record.status]; }
export function formatRecordedMoney(amount: number | null | undefined, currency: string | null | undefined) { if (amount == null) return "공개되지 않음"; if (currency === "KRW") return formatKrw(amount); return `${amount.toLocaleString("ko-KR")} ${currency ?? "(통화 미확인)"}`; }
export function sourceReportedReturn(record: TrackRecord) { return resolvedTrackReturn(record); }
export function calculatedSettlementReturn(record: TrackRecord) { return record.calculatedSettlementReturnPct ?? null; }
function artworkSize(product: HistoricalOfferingView) { const values = [product.artwork.width, product.artwork.height, product.artwork.depth].filter((item): item is number => item != null); return values.length ? `${values.join(" × ")}cm` : "공개되지 않음"; }
function recordDate(product: HistoricalOfferingView) { return product.offering.subscriptionEnd ?? product.offering.subscriptionStart ?? product.offering.liquidatedAt ?? product.offering.soldAt ?? product.offering.asOfDate; }
function exitLabel(record: TrackRecord) { return record.status === "returned" ? "반환 기재액" : "매각 기재액"; }

export function HistoricalProductCard({ product }: { product: HistoricalOfferingView }) {
  const record = product.trackRecord; const exitCurrency = record.exitCurrency ?? record.currency;
  return <article className="art-product-card historical-product-card"><div className="product-image"><Image unoptimized src={product.artwork.imageUrl ?? "/art-placeholder.svg"} alt={`${product.artwork.title} 합성 이미지`} fill sizes="(max-width:720px) 100vw,340px" /><span className="real-data-badge">합성 이력 · 시뮬레이션</span></div><div className="product-card-body"><div className="product-status-row"><span className="status-label">{trackStatusLabel(record)}</span><span className="condition-chip">{product.platform.name}</span></div><h3><Link href={`/products/${product.offering.id}`}>{product.offering.title}</Link></h3><p className="entity-links"><Link href={`/artists/${product.artist.id}`}>{product.artist.nameKo}</Link><span>·</span><span>{product.artwork.title}</span></p><dl className="card-metrics"><div><dt>시뮬레이션 금액</dt><dd>{formatRecordedMoney(product.offering.totalOfferingAmount, product.offering.currency)}</dd></div><div><dt>보유기간</dt><dd>{product.offering.actualHoldingMonths == null ? "공개되지 않음" : `${product.offering.actualHoldingMonths.toFixed(1)}개월`}</dd></div><div><dt>{exitLabel(record)}</dt><dd>{formatRecordedMoney(record.exitAmount, exitCurrency)}</dd></div><div><dt>시뮬레이션 수익률</dt><dd>{formatPercent(sourceReportedReturn(record))}</dd></div></dl><p className="card-headline">상태 : {trackStatusLabel(record)} · 기준일 : {recordDate(product)}</p><p className="table-note">학습과 화면 검증을 위한 합성 이력입니다. 실제 투자 실적이나 원문 기록이 아닙니다.</p><div className="card-actions"><Link className="button button-primary" href={`/products/${product.offering.id}`}>이력 상세 보기</Link></div></div></article>;
}

export function HistoricalProductDetail({ product }: { product: HistoricalOfferingView }) {
  const record = product.trackRecord; const exitCurrency = record.exitCurrency ?? record.currency;
  const fields: Array<[string, string | number | null | undefined]> = [["상태", trackStatusLabel(record)], ["청약 시작일", record.subscriptionStart], ["청약 종료일", record.subscriptionEnd], ["보유기간", record.actualHoldingMonths == null ? null : `${record.actualHoldingMonths.toFixed(1)}개월`], ["매각일", record.soldAt], ["청산일", record.liquidatedAt], ["매각 경로", record.soldPlace], ["시뮬레이션 수익률", sourceReportedReturn(record) == null ? null : `${sourceReportedReturn(record)?.toFixed(2)}%`]];
  return <main id="main-content" className="detail-page"><PageContainer><Breadcrumb items={[{ label: "홈", href: "/" }, { label: "청약 상품·합성 이력", href: "/products?scope=historical" }, { label: product.offering.title }]} /><header className="product-detail-header"><div className="detail-image"><Image unoptimized src={product.artwork.imageUrl ?? "/art-placeholder.svg"} alt={`${product.artwork.title} 합성 이미지`} fill priority sizes="(max-width:720px) 100vw,420px" /><span className="real-data-badge">합성 이력 · 시뮬레이션</span></div><div><span className="status-label">{trackStatusLabel(record)}</span><h1>{product.offering.title}</h1><p className="detail-entities"><Link href={`/artists/${product.artist.id}`}>{product.artist.nameKo}</Link><span>·</span><Link href={`/platforms/${product.platform.id}`}>{product.platform.name}</Link></p><p>실제 플랫폼, 발행사, 거래 기록과 연결되지 않은 합성 시뮬레이션입니다.</p><dl className="header-facts"><div><dt>작품</dt><dd>{product.artwork.title}</dd></div><div><dt>제작연도</dt><dd>{product.artwork.productionYear ?? "공개되지 않음"}</dd></div><div><dt>재료</dt><dd>{product.artwork.medium ?? "공개되지 않음"}</dd></div><div><dt>크기</dt><dd>{artworkSize(product)}</dd></div><div><dt>시뮬레이션 기간</dt><dd>{product.offering.subscriptionStart ?? "미기재"} ~ {product.offering.subscriptionEnd ?? "미기재"}</dd></div><div><dt>기준일</dt><dd>{recordDate(product)}</dd></div></dl></div></header><section className="content-section"><div className="section-heading-art"><div><p className="section-kicker">SYNTHETIC HISTORY</p><h2>시뮬레이션 공모·보유·회수 값</h2></div></div><div className="metric-grid-art"><MetricCard label="시뮬레이션 금액" value={formatRecordedMoney(product.offering.totalOfferingAmount, product.offering.currency)} /><MetricCard label="보유기간" value={product.offering.actualHoldingMonths == null ? "공개되지 않음" : `${product.offering.actualHoldingMonths.toFixed(1)}개월`} /><MetricCard label={exitLabel(record)} value={formatRecordedMoney(product.offering.actualExitAmount, exitCurrency)} /><MetricCard label="정산 기재액" value={formatRecordedMoney(product.offering.actualDistributionAmount, "KRW")} /><MetricCard label="시뮬레이션 수익률" value={formatPercent(sourceReportedReturn(record))} /><MetricCard label="계산 수익률" value={formatPercent(calculatedSettlementReturn(record))} /><MetricCard label="매각일" value={product.offering.soldAt ?? "미기재"} /><MetricCard label="청산일" value={product.offering.liquidatedAt ?? "미기재"} /></div></section><section className="content-section"><h2>합성 이력 필드</h2><div className="table-wrap"><table><thead><tr><th>항목</th><th>값</th></tr></thead><tbody>{fields.map(([label, value]) => <tr key={label}><th>{label}</th><td>{value == null || value === "" ? "미기재" : value}</td></tr>)}</tbody></table></div></section><section className="content-section"><h2>데이터 범위</h2><p className="table-note">이 화면은 합성 데이터만 표시합니다. 원본 payload, 원문 링크, 외부 출처 데이터셋은 제공하지 않습니다.</p></section></PageContainer></main>;
}
