import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import type { AnalysisResult, ChangeLog, Evidence, ProductView, Verdict } from "@/lib/art/types";
import { formatKrw, formatPercent, pricePremiumRate, sumDisclosedCosts, unexplainedDifference } from "@/lib/domain/calculations";
import { statusLabels } from "@/lib/repositories/art-repositories";
import { CompareButton } from "@/components/art/compare-client";
export function PageContainer({children,className=""}:{children:ReactNode;className?:string}){return <div className={`art-shell ${className}`}>{children}</div>}
export function DemoDataBadge(){return <span className="demo-badge">DEMO · 데모 데이터</span>}
export function DataModeBadge({isDemo}:{isDemo:boolean}){return isDemo?<DemoDataBadge/>:<span className="real-data-badge">기존 DB · 공개자료 저장본</span>}
export function AiVerdictBadge({verdict,label}:{verdict:Verdict;label:string}){const icons={worth_considering:"✓",conditional:"◇",caution:"!",danger:"×"};return <span className={`verdict-badge verdict-${verdict}`}><span aria-hidden="true">{icons[verdict]}</span>{label}</span>}
export function Breadcrumb({items}:{items:Array<{label:string;href?:string}>}){return <nav className="breadcrumb" aria-label="현재 위치">{items.map((item,i)=><span key={`${item.label}-${i}`}>{i? <span aria-hidden="true">/</span>:null}{item.href?<Link href={item.href}>{item.label}</Link>:<strong aria-current="page">{item.label}</strong>}</span>)}</nav>}
export function MetricCard({label,value,note}:{label:string;value:string;note?:string}){return <article className="metric-card-art"><span>{label}</span><strong>{value}</strong>{note?<small>{note}</small>:null}</article>}
export function EmptyState({title="조건에 맞는 분석 상품이 없습니다.",description="필터를 줄이거나 다른 검색어를 입력하세요."}:{title?:string;description?:string}){return <section className="state-panel"><strong>{title}</strong><p>{description}</p></section>}
export function NotFoundState({kind="상품"}:{kind?:string}){return <section className="state-panel state-large"><strong>{kind} 데이터를 찾을 수 없습니다.</strong><p>잘못된 주소이거나 분석 대상에서 제외된 항목입니다.</p><Link className="button button-primary" href="/products">상품 목록으로</Link></section>}
export function ProductCard({product,compact=false}:{product:ProductView;compact?:boolean}){const premium=pricePremiumRate(product.offering.totalOfferingAmount,product.offering.acquisitionPrice);return <article className={`art-product-card ${compact?"compact":""}`}>
 <div className="product-image"><Image src={product.artwork.imageUrl??"/demo-art/art-1.svg"} alt={`${product.artwork.title} ${product.offering.isDemo?"데모 작품 이미지":"원본 이미지 미저장 placeholder"}`} fill sizes="(max-width: 720px) 100vw, 340px"/><DataModeBadge isDemo={product.offering.isDemo}/></div>
 <div className="product-card-body"><div className="product-status-row"><span className="status-label">{statusLabels[product.offering.status]}</span><AiVerdictBadge verdict={product.analysis.verdict} label={product.analysis.verdictLabel}/></div>
 <h3><Link href={`/products/${product.offering.id}`}>{product.offering.title}</Link></h3>
 <p className="entity-links"><Link href={`/artists/${product.artist.id}`}>{product.artist.nameKo}</Link><span>·</span><Link href={`/platforms/${product.platform.id}`}>{product.platform.name}</Link></p>
 {!compact?<dl className="card-metrics"><div><dt>최소 투자금</dt><dd>{formatKrw(product.offering.minimumInvestment)}</dd></div><div><dt>총 공모금액</dt><dd>{formatKrw(product.offering.totalOfferingAmount)}</dd></div><div><dt>작품 취득가</dt><dd>{formatKrw(product.offering.acquisitionPrice)}</dd></div><div><dt>공모가 차이율</dt><dd>{formatPercent(premium)}</dd></div></dl>:null}
 <p className="card-headline">{product.analysis.headline}</p>{!compact?<ul className="reason-list compact-list">{product.analysis.keyReasons.slice(0,2).map(r=><li key={r.title}>{r.finding}</li>)}</ul>:null}
 <div className="card-actions"><Link className="button button-primary" href={`/products/${product.offering.id}`}>상품 분석 보기</Link><CompareButton productId={product.offering.id}/></div></div></article>}
export function AiJudgmentPanel({analysis}:{analysis:AnalysisResult}){return <section className={`judgment-panel judgment-${analysis.verdict}`}><div><p className="section-kicker">AI 청약 판단</p><AiVerdictBadge verdict={analysis.verdict} label={analysis.verdictLabel}/><h2>{analysis.headline}</h2></div><ul className="key-reason-grid">{analysis.keyReasons.map(r=><li key={r.title}><strong>{r.title}</strong><span>{r.finding}</span><p>{r.implication}</p></li>)}</ul><p className="judgment-summary">{analysis.summary}</p></section>}
export function EvidenceAccordion({evidence}:{evidence:Evidence[]}){return <div className="evidence-list-art">{evidence.map((ev)=><details key={ev.id}><summary><span>{ev.claim}</span><small>{ev.sourceTitle} · 기준일 {ev.asOfDate??"없음"}</small></summary><dl><div><dt>사용한 값</dt><dd><code>{JSON.stringify(ev.value)}</code></dd></div><div><dt>발행 주체</dt><dd>{ev.sourcePublisher}</dd></div><div><dt>출처 유형</dt><dd>{ev.sourceType}</dd></div><div><dt>계산식</dt><dd>{ev.formula??"원문 값"}</dd></div></dl>{ev.notes?<p>{ev.notes}</p>:null}{ev.sourceUrl?<a href={ev.sourceUrl} target="_blank" rel="noopener noreferrer">관련 근거 열기 ↗</a>:null}</details>)}</div>}
export function PriceBridgeChart({product}:{product:ProductView}){const {offering}=product;const total=offering.totalOfferingAmount??0;const costs=sumDisclosedCosts(offering.disclosedCosts);const costList=<ul className="cost-list">{offering.disclosedCosts.map((cost)=><li key={cost.category}><span>{cost.label}</span><strong>{formatKrw(cost.amount)}</strong></li>)}</ul>;if(offering.acquisitionPrice==null)return <figure className="chart-card"><figcaption><strong>취득가와 공모금액</strong><span>단위: 원 · 기준일 {offering.asOfDate}</span></figcaption><div className="chart-empty"><strong>취득가 데이터 없음</strong><p>감정가를 취득가로 대체하지 않았습니다.</p></div>{costList}<p className="chart-summary">공개된 비용 {formatKrw(costs)}의 세부 항목은 표시하지만, 취득가가 없어 미설명 차액은 계산하지 않았습니다.</p></figure>;const unknown=unexplainedDifference(total,offering.acquisitionPrice,offering.disclosedCosts)??0;const max=Math.max(total,1);return <figure className="chart-card"><figcaption><strong>취득가와 공모금액</strong><span>단위: 원 · 기준일 {offering.asOfDate}</span></figcaption><div className="bar-chart"><div><span>작품 취득가</span><i style={{width:`${offering.acquisitionPrice/max*100}%`}}/><b>{formatKrw(offering.acquisitionPrice)}</b></div><div><span>총 공모금액</span><i style={{width:"100%"}}/><b>{formatKrw(total)}</b></div></div><div className="stacked-bar" aria-label={`취득가 ${offering.acquisitionPrice}원, 공개비용 ${costs}원, 미설명 차액 ${unknown}원`}><span className="stack-acq" style={{width:`${offering.acquisitionPrice/total*100}%`}}>취득가</span><span className="stack-cost" style={{width:`${costs/total*100}%`}}>공개 비용</span>{unknown>0?<span className="stack-unknown" style={{width:`${unknown/total*100}%`}}>미설명</span>:null}</div>{costList}<p className="chart-summary">공모금액은 취득가, 공개 비용 {formatKrw(costs)}, 설명되지 않는 차액 {formatKrw(unknown)}으로 나뉩니다.</p></figure>}
export function AuctionVolumeChart({product}:{product:ProductView}){if(!product.annualMetrics.length)return <div className="chart-empty"><strong>연도별 경매 집계 없음</strong><p>플랫폼 기재 사례를 독립 경매 집계로 대체하지 않았습니다.</p></div>;const max=Math.max(...product.annualMetrics.map(x=>x.offered),1);return <figure className="chart-card"><figcaption><strong>{product.annualMetrics.length>=5?"최근 5년":"연결 연도"} 출품·낙찰</strong><span>단위: 건</span></figcaption><div className="column-chart">{product.annualMetrics.map(m=><div key={m.year}><div className="columns"><i className="offered" style={{height:`${m.offered/max*130}px`}} title={`출품 ${m.offered}건`}/><i className="sold" style={{height:`${m.sold/max*130}px`}} title={`낙찰 ${m.sold}건`}/></div><span>{m.year}</span><small>{m.offered}/{m.sold}</small></div>)}</div><div className="chart-legend"><span><i className="legend-offered"/>출품</span><span><i className="legend-sold"/>낙찰</span></div><p className="chart-summary">각 연도의 출품 건수와 실제 낙찰 건수를 함께 표시합니다.</p></figure>}
export function PriceTrendChart({product}:{product:ProductView}){const points=product.annualMetrics.filter((item):item is typeof item&{medianPrice:number}=>item.medianPrice!=null);if(!points.length)return <div className="chart-empty"><strong>중위 낙찰가 데이터 없음</strong><p>평균·총액을 중위값으로 대체하지 않았습니다.</p></div>;const vals=points.map(x=>x.medianPrice);const min=Math.min(...vals),max=Math.max(...vals);const pts=vals.map((v,i)=>`${20+i*(280/(vals.length-1||1))},${145-(v-min)/(max-min||1)*105}`).join(" ");return <figure className="chart-card"><figcaption><strong>연도별 중위 낙찰가</strong><span>단위: 백만원</span></figcaption><svg className="line-chart" viewBox="0 0 320 170" role="img" aria-label={points.map(m=>`${m.year}년 ${Math.round(m.medianPrice/1000000)}백만원`).join(", ")}><line x1="20" y1="145" x2="300" y2="145"/><polyline points={pts}/>{points.map((m,i)=><g key={m.year}><circle cx={20+i*(280/(points.length-1||1))} cy={145-(m.medianPrice-min)/(max-min||1)*105} r="4"/><text x={20+i*(280/(points.length-1||1))} y="163">{String(m.year).slice(2)}</text></g>)}</svg><p className="chart-summary">중위값이 공개된 연도만 표시하며 평균·총액으로 대체하지 않습니다.</p></figure>}
export function PlatformOutcomeChart({product}:{product:ProductView}){const groups=[['청산 완료',product.trackRecords.filter(t=>t.status==='liquidated').length,'good'],['매각 완료',product.trackRecords.filter(t=>t.status==='sold').length,'good'],['지연 청산',product.trackRecords.filter(t=>t.status==='delayed').length,'warn'],['운용 중',product.trackRecords.filter(t=>t.status==='operating').length,'neutral'],['미매각·반환',product.trackRecords.filter(t=>t.status==='unsold').length,'danger']]; const total=Math.max(product.trackRecords.length,1);return <figure className="chart-card"><figcaption><strong>과거 상품 상태 분포</strong><span>총 {product.trackRecords.length}개</span></figcaption><div className="outcome-bar">{groups.filter(g=>Number(g[1])>0).map(g=><span className={`outcome-${g[2]}`} style={{width:`${Number(g[1])/total*100}%`}} key={String(g[0])}>{g[0]} {g[1]}</span>)}</div><ul className="chart-data-list">{groups.map(g=><li key={String(g[0])}><span>{g[0]}</span><strong>{g[1]}개</strong></li>)}</ul><p className="chart-summary">매각 완료와 청산 완료를 같은 상태로 합치지 않았습니다.</p></figure>}
export function ExpectedActualChart({product}:{product:ProductView}){const complete=product.trackRecords.filter(t=>t.actualHoldingMonths!=null);if(!complete.length)return <div className="chart-empty"><strong>실제 보유기간 데이터 없음</strong><p>미확인 값을 0개월로 표시하지 않았습니다.</p></div>;const max=Math.max(36,...complete.map(t=>t.actualHoldingMonths??0));return <figure className="chart-card"><figcaption><strong>목표와 실제 보유기간</strong><span>단위: 개월</span></figcaption><div className="expected-list">{complete.slice(0,6).map(t=><div key={t.id}><span>{t.productName}</span><div><i className="expected" style={{width:`${(t.targetHoldingMonths??0)/max*100}%`}}>목표 {t.targetHoldingMonths}</i><i className="actual" style={{width:`${(t.actualHoldingMonths??0)/max*100}%`}}>실제 {t.actualHoldingMonths}</i></div></div>)}</div><p className="chart-summary">기간이 길어진 상품은 보관·보험 비용과 회수 시점 위험이 함께 커질 수 있습니다.</p></figure>}

export function ChangeLogTable({items}:{items:ChangeLog[]}){return <div className="table-wrap"><table><caption className="sr-only">분석 데이터 변경 이력</caption><thead><tr><th>변경일</th><th>필드</th><th>이전 값</th><th>새 값</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.changedAt}</td><td>{item.fieldPath}</td><td>{String(item.previousValue??"-")}</td><td>{String(item.newValue??"-")}</td></tr>)}</tbody></table></div>}
