import Link from "next/link";
import s from "./art.module.css";
import { ArtCompareSection } from "./art-compare-section";
import { money, type ArtFact, type ArtViewModel } from "./art-view-model";

const verdictLabel = { match: "일치", unverifiable: "대조 불가" } as const;
function FactCard({ fact }: { fact: ArtFact }) {
  const difference = fact.acquisition != null && fact.issuanceCost != null && fact.offeringAmount != null ? fact.offeringAmount - fact.acquisition - fact.issuanceCost : null;
  return <article className={s.factCard}><span className={s.factCardHead}><span className={s.factLabel}>{fact.label}</span><span className={`${s.verdictChip} ${fact.verdict === "match" ? s.verdictMatch : s.verdictUnknown}`}>{verdictLabel[fact.verdict]}</span></span><p className={s.factStatusNote}>{fact.statusNote}</p><dl className={s.factMetaRow}><div className={s.factMeta}><dt>공모금액</dt><dd>{money(fact.offeringAmount)}</dd></div><div className={s.factMeta}><dt>기준일</dt><dd>{fact.asOf}</dd></div><div className={s.factMeta}><dt>상태</dt><dd>{fact.lifecycle}</dd></div></dl><p className={s.priceChain}>{fact.priceChain}</p><p className={s.factFinding}>{fact.finding}</p>{fact.sources.length ? <ul className={s.factSources}>{fact.sources.map((source) => <li key={source.rcpNo}><a className={s.sourceLink} href={source.url} target="_blank" rel="noopener noreferrer">{source.label} ↗</a><span className={s.sourceMeta}>기준 {source.asOf}</span></li>)}</ul> : <p className={s.sourceEmpty}>{fact.sourceNote}</p>}<details className={s.detail}><summary className={s.detailToggle}>상세 · 문서 좌표와 구성 검산 보기</summary><dl className={s.detailBody}><div className={s.detailBlock}><dt>공시 문서</dt>{fact.sources.length ? fact.sources.map((source) => <dd key={source.rcpNo} className={s.detailMono}>{source.label} · 접수번호 {source.rcpNo} · {source.asOf}</dd>) : <dd>{fact.sourceNote}</dd>}</div><div className={s.detailBlock}><dt>공모가 구성 검산</dt><dd className={s.detailMono}>{difference == null ? "취득가와 발행비용이 공시에 분리 기재되지 않아 구성 검산 대상이 아닙니다." : `취득가 ${money(fact.acquisition)} + 발행비용 ${money(fact.issuanceCost)} = 공모가 ${money(fact.offeringAmount)} · 차액 ${difference.toLocaleString("ko-KR")}원`}</dd></div><div className={s.detailBlock}><dt>공시 기재 순서</dt><dd className={s.detailMono}>{fact.priceChain}</dd></div><div className={s.detailBlock}><dt>한계</dt><dd>{fact.limitation}</dd></div><div className={s.detailBlock}><dt>근거 상태 뜻</dt><dd>{verdictLabel[fact.verdict]} — {fact.verdict === "match" ? "공시에 적힌 내용이 공적 원장의 기록과 같았다는 뜻입니다" : "대조할 공적 원장 자료가 아직 없었다는 뜻입니다"}</dd></div></dl></details></article>;
}
function CompositionChart({ facts }: { facts: ArtFact[] }) { return <figure className={s.chartCard}><figcaption className={s.chartCaption}><strong>상품별 공모금액 구성</strong><span>취득가 + 발행비용</span></figcaption><div className={s.chartLegend}><span><i className={s.legendAcq} />취득가</span><span><i className={s.legendCost} />발행비용</span></div><div className={s.compRows}>{facts.map((fact) => <div className={s.compRow} key={fact.id}><div className={s.compRowHead}><strong>{fact.label}</strong><span>{money(fact.offeringAmount)}</span></div>{fact.acquisition != null && fact.issuanceCost != null && fact.offeringAmount ? <div className={s.stackBar}><span className={s.stackAcq} style={{ width: `${fact.acquisition / fact.offeringAmount * 100}%` }}>취득가</span><span className={s.stackCost} style={{ width: `${fact.issuanceCost / fact.offeringAmount * 100}%` }}>발행비용</span></div> : <p className={s.stackNone}>구성 분리 기재 없음</p>}</div>)}</div></figure>; }
function AmountChart({ facts }: { facts: ArtFact[] }) { const max = Math.max(...facts.map((fact) => fact.offeringAmount ?? 0), 1); return <figure className={s.chartCard}><figcaption className={s.chartCaption}><strong>상품별 공모금액 비교</strong><span>단위 : 원</span></figcaption><div className={s.colChart} role="img" aria-label={facts.map((fact) => `${fact.label} ${fact.offeringAmount?.toLocaleString("ko-KR")}원`).join(", ")}>{facts.map((fact) => <div className={s.colItem} key={fact.id}><span className={s.colBarWrap}><span className={s.colValue}>{Math.round((fact.offeringAmount ?? 0) / 100_000_000)}억</span><span className={s.colBar} style={{ height: `${(fact.offeringAmount ?? 0) / max * 100}%` }} /></span><span className={s.colLabel}>{fact.label}</span></div>)}</div></figure>; }
export function ArtLiveSection({ model }: { model: ArtViewModel }) { const platformCounts = model.historicalByPlatform; return <div><p className={s.factLead}>발행사가 전자공시(DART)에 낸 증권신고서·투자설명서·발행실적보고서에서 대조한 공모가 구성 사실입니다. 공시 접수일 순으로 나열했으며, 작가·작품·플랫폼 식별 정보는 이 단계 화면에 올리지 않습니다. 판정은 공시와 공공원장의 대조 결과입니다.</p><p className={s.absenceNote}>독립 경매 낙찰·플랫폼 청산 대조 수치는 아직 연결되지 않아, 이 화면에는 경매·회수 관련 차트 대신 공시 원문에서 대조한 사실과 공모금액 구성만 싣습니다. 자료가 없는 항목은 대조 불가 또는 기재 없음으로 정직하게 표기합니다.</p><div className={s.factGrid}>{model.facts.map((fact) => <FactCard key={fact.id} fact={fact} />)}</div><section className={s.artSub} aria-labelledby="art-charts"><h3 className={s.subhead} id="art-charts">공모금액 구성·비교 (공시 수치)</h3><p className={s.chartSectionLead}>공시에 분리 기재된 취득가와 발행비용, 그리고 다섯 상품의 공모금액을 그대로 옮긴 그래프입니다. 경매·회수처럼 다른 원장 대조가 필요한 수치는 넣지 않았습니다.</p><div className={s.chartPair}><CompositionChart facts={model.facts} /><AmountChart facts={model.facts} /></div></section><section className={s.artSub} aria-labelledby="art-compare"><h3 className={s.subhead} id="art-compare">상품 나란히 보기</h3><p className={s.compareLead}>상품 두셋을 골라 공시 사실을 나란히 놓고 봅니다. 선택은 주소(URL)에 담겨 그대로 공유할 수 있습니다.</p><ArtCompareSection facts={model.facts} /></section><details className={s.calcBlock}><summary className={s.calcToggle}>계산 기준 (게이트 무관 산식)</summary><div className={s.calcBody}><p>이 화면의 수치는 다음 산식으로만 계산합니다. 모두 공시에 적힌 값에서 나오며, 최종 투자 판단을 대신하지 않습니다.</p><p className={s.calcFormula}>구성 검산 : 취득가 + 발행비용 = 공모가. 차액이 0원이면 산식이 성립하고, 분리 기재가 없으면 검산 대상이 아닙니다.</p><p className={s.calcFormula}>차이율 : (공모가 − 기준가격) ÷ 기준가격 × 100. 기준가격이 공시에 없으면 계산하지 않습니다.</p><p>산식은 값 사이의 산술 관계만 확인합니다. 작품 가치나 처분 가능성, 미래 가격은 이 산식의 대상이 아닙니다.</p></div></details><p className={s.historicalNote}>플랫폼 3곳의 과거 공개 이력 저장본 {model.historicalTotal.toLocaleString("ko-KR")}건(플랫폼 A {platformCounts[0] ?? 0}건 · 플랫폼 B {platformCounts[1] ?? 0}건 · 플랫폼 C {platformCounts[2] ?? 0}건)을 확보했으나, 이용 조건 확인 절차가 진행 중이라 이 화면에는 집계 건수만 싣습니다. 개별 항목과 원문은 각 플랫폼에서 직접 확인해야 합니다.</p><section className={s.artSub} aria-labelledby="evidence-copilot-bridge"><h3 className={s.subhead} id="evidence-copilot-bridge">Evidence Copilot</h3><p className={s.compareLead}>근거를 더 물어보려면 상품 문맥이 필요합니다. 아래 링크에서 해당 상품의 Evidence Copilot을 엽니다.</p><div className={s.comparePicker}>{model.facts.map((fact) => <Link className={s.compareChip} key={fact.id} href={`/products/${fact.realId}#evidence-copilot`}>{fact.label} Evidence Copilot</Link>)}</div></section></div>; }
