import Link from "next/link";
import s from "./art.module.css";
import { ArtCompareSection } from "./art-compare-section";
import { money, type ArtFact, type ArtViewModel } from "./art-view-model";

const verdictLabel = { match: "일치", unverifiable: "대조 불가" } as const;
function FactCard({ fact }: { fact: ArtFact }) {
  const difference = fact.acquisition != null && fact.issuanceCost != null && fact.offeringAmount != null ? fact.offeringAmount - fact.acquisition - fact.issuanceCost : null;
  return <article className={s.factCard}><span className={s.factCardHead}><span className={s.factLabel}>{fact.label}</span><span className={`${s.verdictChip} ${fact.verdict === "match" ? s.verdictMatch : s.verdictUnknown}`}>{verdictLabel[fact.verdict]}</span></span><p className={s.factStatusNote}>{fact.statusNote}</p><dl className={s.factMetaRow}><div className={s.factMeta}><dt>공모금액</dt><dd>{money(fact.offeringAmount)}</dd></div><div className={s.factMeta}><dt>기준일</dt><dd>{fact.asOf}</dd></div><div className={s.factMeta}><dt>상태</dt><dd>{fact.lifecycle}</dd></div></dl><p className={s.priceChain}>{fact.priceChain}</p><p className={s.factFinding}>{fact.finding}</p>{fact.sources.length ? <ul className={s.factSources}>{fact.sources.map((source) => <li key={source.rcpNo}><span className={s.sourceLink}>{source.label}</span><span className={s.sourceMeta}>기준 {source.asOf}</span></li>)}</ul> : <p className={s.sourceEmpty}>{fact.sourceNote}</p>}<details className={s.detail}><summary className={s.detailToggle}>상세 · 합성 구성 검산 보기</summary><dl className={s.detailBody}><div className={s.detailBlock}><dt>합성 데이터</dt>{fact.sources.length ? fact.sources.map((source) => <dd key={source.rcpNo} className={s.detailMono}>{source.label} · 접수번호 {source.rcpNo} · {source.asOf}</dd>) : <dd>{fact.sourceNote}</dd>}</div><div className={s.detailBlock}><dt>공모가 구성 검산</dt><dd className={s.detailMono}>{difference == null ? "합성 취득가와 비용이 분리되지 않아 구성 검산 대상이 아닙니다." : `취득가 ${money(fact.acquisition)} + 발행비용 ${money(fact.issuanceCost)} = 공모가 ${money(fact.offeringAmount)} · 차액 ${difference.toLocaleString("ko-KR")}원`}</dd></div><div className={s.detailBlock}><dt>합성 데이터 구성</dt><dd className={s.detailMono}>{fact.priceChain}</dd></div><div className={s.detailBlock}><dt>한계</dt><dd>{fact.limitation}</dd></div><div className={s.detailBlock}><dt>근거 상태 뜻</dt><dd>{verdictLabel[fact.verdict]} — {fact.verdict === "match" ? "합성 데이터의 산술 관계가 표시되었다는 뜻입니다" : "실제 원문과 대조하지 않는다는 뜻입니다"}</dd></div></dl></details></article>;
}
function CompositionChart({ facts }: { facts: ArtFact[] }) { return <figure className={s.chartCard}><figcaption className={s.chartCaption}><strong>상품별 공모금액 구성</strong><span>취득가 + 발행비용</span></figcaption><div className={s.chartLegend}><span><i className={s.legendAcq} />취득가</span><span><i className={s.legendCost} />발행비용</span></div><div className={s.compRows}>{facts.map((fact) => <div className={s.compRow} key={fact.id}><div className={s.compRowHead}><strong>{fact.label}</strong><span>{money(fact.offeringAmount)}</span></div>{fact.acquisition != null && fact.issuanceCost != null && fact.offeringAmount ? <div className={s.stackBar}><span className={s.stackAcq} style={{ width: `${fact.acquisition / fact.offeringAmount * 100}%` }}>취득가</span><span className={s.stackCost} style={{ width: `${fact.issuanceCost / fact.offeringAmount * 100}%` }}>발행비용</span></div> : <p className={s.stackNone}>구성 분리 기재 없음</p>}</div>)}</div></figure>; }
function AmountChart({ facts }: { facts: ArtFact[] }) { const max = Math.max(...facts.map((fact) => fact.offeringAmount ?? 0), 1); return <figure className={s.chartCard}><figcaption className={s.chartCaption}><strong>상품별 공모금액 비교</strong><span>단위 : 원</span></figcaption><div className={s.colChart} role="img" aria-label={facts.map((fact) => `${fact.label} ${fact.offeringAmount?.toLocaleString("ko-KR")}원`).join(", ")}>{facts.map((fact) => <div className={s.colItem} key={fact.id}><span className={s.colBarWrap}><span className={s.colValue}>{Math.round((fact.offeringAmount ?? 0) / 100_000_000)}억</span><span className={s.colBar} style={{ height: `${(fact.offeringAmount ?? 0) / max * 100}%` }} /></span><span className={s.colLabel}>{fact.label}</span></div>)}</div></figure>; }
export function ArtLiveSection({ model }: { model: ArtViewModel }) { return <div><p className={s.factLead}>합성 상품의 공모가 구성 시뮬레이션입니다. 실제 공시, 작가, 작품, 플랫폼, 투자 기록과 연결되지 않습니다.</p><p className={s.absenceNote}>이 화면은 합성 공모금액과 시뮬레이션 구성만 표시합니다. 실제 경매·회수·공시 수치는 제공하지 않습니다.</p><div className={s.factGrid}>{model.facts.map((fact) => <FactCard key={fact.id} fact={fact} />)}</div><section className={s.artSub} aria-labelledby="art-charts"><h3 className={s.subhead} id="art-charts">합성 공모금액 구성·비교</h3><p className={s.chartSectionLead}>합성 취득가, 합성 비용, 합성 공모금액을 표시한 시뮬레이션 그래프입니다.</p><div className={s.chartPair}><CompositionChart facts={model.facts} /><AmountChart facts={model.facts} /></div></section><section className={s.artSub} aria-labelledby="art-compare"><h3 className={s.subhead} id="art-compare">상품 나란히 보기</h3><p className={s.compareLead}>합성 상품을 골라 시뮬레이션 값을 나란히 비교합니다.</p><ArtCompareSection facts={model.facts} /></section><details className={s.calcBlock}><summary className={s.calcToggle}>계산 기준 (게이트 무관 산식)</summary><div className={s.calcBody}><p>이 화면의 수치는 합성 데이터에서 계산하며, 실제 투자 판단에 사용할 수 없습니다.</p><p className={s.calcFormula}>구성 검산 : 합성 취득가 + 합성 비용 = 합성 공모가.</p><p className={s.calcFormula}>차이율은 합성 값 사이의 산술 관계만 표시합니다.</p><p>산식은 실제 작품 가치, 처분 가능성, 미래 가격을 나타내지 않습니다.</p></div></details><p className={s.historicalNote}>가상 플랫폼의 합성 이력 {model.historicalTotal.toLocaleString("ko-KR")}건을 UI 검증용으로 제공합니다. 실제 원문, 거래, 플랫폼 정보는 포함하지 않습니다.</p><section className={s.artSub} aria-labelledby="evidence-copilot-bridge"><h3 className={s.subhead} id="evidence-copilot-bridge">Evidence Copilot</h3><p className={s.compareLead}>근거를 더 물어보려면 상품 문맥이 필요합니다. 아래 링크에서 해당 상품의 Evidence Copilot을 엽니다.</p><div className={s.comparePicker}>{model.facts.map((fact) => <Link className={s.compareChip} key={fact.id} href={`/products/${fact.realId}#evidence-copilot`}>{fact.label} Evidence Copilot</Link>)}</div></section></div>; }
