import {loadCatalog} from "./api.js";
import {artComparableStats,artEvidenceVerdict,artGap,artShares,broadGapMessage,broadStats,evidenceConfidence,lifecycleLabel,lifecycleState,percent,priceBurden,pricing,realEstateComparison,recoveryRisk,searchProducts,sourceExpired,won} from "./calculations.js";

const $=id=>document.getElementById(id);
const S={products:[],issuers:[],apiStatus:{},lifecycle:"ALL",asset:"ALL",query:"",selected:null,compare:[],loadError:false};
const text=(node,value)=>(node.textContent=value??"확인 불가",node);
function el(tag,klass,value){const node=document.createElement(tag);if(klass)node.className=klass;if(value!=null)text(node,value);return node}
function kst(value){if(!value)return "확인 불가";if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const d=new Date(value);return Number.isNaN(d.getTime())?String(value):new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(d).replace(/\. /g,"-").replace(/\.$/,"")+" KST"}
function validHttp(value){try{return ["http:","https:"].includes(new URL(value).protocol)}catch{return false}}
function sqm(v){return Number.isFinite(v)?`${v}㎡ (${(v/3.305785).toFixed(2)}평)`:"확인 불가"}
function facts(rows){const out=el("dl","fact-grid");rows.forEach(([name,value])=>{const box=el("div","fact");box.append(el("dt",null,name),el("dd",null,value));out.append(box)});return out}
function link(label,url){try{const parsed=new URL(url);if(!validHttp(parsed.href))throw new Error("unsupported protocol");const a=el("a",null,label);a.href=parsed.href;a.target="_blank";a.rel="noopener noreferrer";return a}catch{return el("span","muted",`${label} : 확인 불가`)}}
function section(title,...children){const node=el("section","detail-section");node.append(el("h3",null,title),...children.filter(Boolean));return node}
function table(caption,headers,rows){const wrap=el("div","table-scroll"),t=document.createElement("table"),cap=el("caption",null,caption),thead=document.createElement("thead"),tr=document.createElement("tr"),tbody=document.createElement("tbody");headers.forEach(h=>{const th=el("th",null,h);th.scope="col";tr.append(th)});thead.append(tr);rows.forEach(values=>{const row=document.createElement("tr");values.forEach(v=>row.append(el("td",null,v)));tbody.append(row)});t.append(cap,thead,tbody);wrap.append(t);return wrap}
function details(summary,...children){const node=document.createElement("details");node.className="technical";node.append(el("summary",null,summary),...children.filter(Boolean));return node}
function statusClass(value){return value.includes("확인 불가")?"status unknown":value.includes("제한")||value.includes("필요")?"status warn":value.includes("완료")?"status okay":"status"}

const lifecycleTabs=[['ALL','전체 상태'],['UPCOMING','공모 예정'],['SUBSCRIPTION','청약 중'],['OPERATING','운용 중'],['COMPLETED','매각·상환 완료']];
function filteredProducts(){return searchProducts(S.products,S.query).filter(p=>(S.asset==="ALL"||p.category===S.asset)&&(S.lifecycle==="ALL"||lifecycleState(p)===S.lifecycle))}
function allVisibleProducts(){return searchProducts(S.products,S.query)}
function focusFilter(rootId,value){[...$(rootId).querySelectorAll("button")].find(button=>button.dataset.value===value)?.focus()}
function focusCompare(id){[...$("product-cards").querySelectorAll(".compare-toggle")].find(button=>button.dataset.productId===id)?.focus()}
function renderFilters(){const lifecycleRoot=$("lifecycle-tabs"),assetRoot=$("asset-filter"),searched=allVisibleProducts(),lifecycleScope=searched.filter(p=>S.asset==="ALL"||p.category===S.asset),assetScope=searched.filter(p=>S.lifecycle==="ALL"||lifecycleState(p)===S.lifecycle);lifecycleRoot.replaceChildren();lifecycleTabs.forEach(([value,label])=>{const count=value==="ALL"?lifecycleScope.length:lifecycleScope.filter(p=>lifecycleState(p)===value).length,b=el("button","filter-button",`${label} ${count}`);b.type="button";b.dataset.value=value;b.setAttribute("aria-pressed",String(S.lifecycle===value));b.onclick=()=>{S.lifecycle=value;render();focusFilter("lifecycle-tabs",value)};lifecycleRoot.append(b)});assetRoot.replaceChildren();[['ALL','전체 자산'],['부동산','부동산'],['미술품','미술품']].forEach(([value,label])=>{const count=value==="ALL"?assetScope.length:assetScope.filter(p=>p.category===value).length,b=el("button","filter-button",`${label} ${count}`);b.type="button";b.dataset.value=value;b.setAttribute("aria-pressed",String(S.asset===value));b.onclick=()=>{S.asset=value;render();focusFilter("asset-filter",value)};assetRoot.append(b)});const outside=lifecycleScope.filter(p=>["OUTSIDE_FILTER","UNCONFIRMED"].includes(lifecycleState(p))).length;$("outside-note").textContent=S.lifecycle==="ALL"&&outside?`전체 상태에는 탭 분류 기준에 직접 대응하지 않는 원문 상태 ${outside}건을 함께 표시합니다.`:""}
function card(p){const price=pricing(p),risk=recoveryRisk(p),confidence=evidenceConfidence(p),burden=priceBurden(p),article=el("article","product-card"),top=el("div","card-top"),title=el("h3",null,p.name),open=el("button","card-open","상세 보기");article.dataset.productId=p.id;if(S.selected===p.id){article.classList.add("selected");article.dataset.selected="true";article.setAttribute("aria-current","true")}open.type="button";open.onclick=()=>{S.selected=p.id;renderCards();renderDetail(true);$("detail").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})};top.append(title,open);const state=lifecycleState(p);article.append(top,el("p",statusClass(lifecycleLabel(state)),lifecycleLabel(state)),el("p","card-status",p.status||"상태 확인 불가"),facts([["공모금액",won(price.offering)],["기초자산가",won(price.base)],["공모 프리미엄",percent(price.premium)],["가격 부담",burden.value],["회수 위험",risk.value],["근거 신뢰도",confidence.value]]));const compare=el("button","compare-toggle",S.compare.includes(p.id)?"비교에서 제외":"비교에 담기");compare.type="button";compare.dataset.productId=p.id;compare.setAttribute("aria-pressed",String(S.compare.includes(p.id)));compare.onclick=()=>toggleCompare(p.id);article.append(compare);return article}
function renderCards(){const root=$("product-cards"),products=filteredProducts();root.replaceChildren();const empty=$("cards-empty");empty.hidden=!!products.length;empty.textContent=S.loadError?"자료를 불러오지 못했습니다.":"필터 조건에 맞는 상품이 없습니다.";products.forEach(p=>root.append(card(p)))}
function toggleCompare(id){const exists=S.compare.includes(id);if(exists){S.compare=S.compare.filter(x=>x!==id);$("compare-message").textContent="비교 상품에서 제외했습니다."}else if(S.compare.length>=3){$("compare-message").textContent="비교는 최대 3개 상품까지 가능합니다.";return}else{S.compare=[...S.compare,id];$("compare-message").textContent="비교 상품에 담았습니다."}renderCards();renderCompare();focusCompare(id)}
function metricForCompare(p){const price=pricing(p);return [p.name,p.category,lifecycleLabel(lifecycleState(p)),won(price.offering),won(price.base),percent(price.premium),priceBurden(p).value,recoveryRisk(p).value,evidenceConfidence(p).value]}
function renderCompare(){const root=$("compare-content"),products=S.compare.map(id=>S.products.find(p=>p.id===id)).filter(Boolean);root.replaceChildren();if(products.length<2){root.append(el("p","muted","서로 다른 상품 2개를 담으면 비교표를 표시합니다."));return}root.append(table("선택 상품 비교",["상품","자산","상태 분류","공모금액","기초자산가","공모 프리미엄","가격 부담","회수 위험","근거 신뢰도"],products.map(metricForCompare)));const clear=el("button","secondary-button","비교 비우기");clear.type="button";clear.onclick=()=>{S.compare=[];$("compare-message").textContent="비교 상품을 비웠습니다.";renderCards();renderCompare();$("compare-title").setAttribute("tabindex","-1");$("compare-title").focus()};root.append(clear)}

function sourceBadges(p){const out=el("div","sources");(p.sources||[]).forEach(s=>{const expired=sourceExpired(s.as_of,p.as_of),state=expired===null?"unknown":expired?"expired":"";out.append(el("span",`source ${state}`,`${s.label} · ${kst(s.as_of)}`))});return out}
function commonSnapshot(p){const price=pricing(p),risk=recoveryRisk(p),confidence=evidenceConfidence(p),burden=priceBurden(p),a=p.asset||{},assetRows=p.category==="부동산"?[["주소",a.address||"확인 불가"],["자산 유형",a.asset_type||"확인 불가"],["대지 / 연면적",sqm(a.site_area_m2)+" / "+sqm(a.gross_floor_area_m2)]]:[["작가 / 제목",`${a.artist||"확인 불가"} / ${a.title||"확인 불가"}`],["연도 / 재료",`${a.year??"확인 불가"} / ${a.material||"확인 불가"}`],["크기",a.size||"확인 불가"]];return section("한눈에 판정",facts([["원문 상태",p.status||"확인 불가"],["상태 분류",lifecycleLabel(lifecycleState(p))],...assetRows,["공모금액",won(price.offering)],["기초자산가",won(price.base)],["공모 프리미엄",percent(price.premium)],["가격 부담",burden.value],["회수 위험",risk.value],["근거 신뢰도",confidence.value]]),el("p","notice",p.status_detail||"상태 상세 확인 불가"),el("p","data-rule",`데이터 품질 규칙 : 기준일 ${kst(p.as_of)} 기준의 저장 원문과 계산값입니다. 개인별 투자 판단 또는 매수·매도 권유가 아닙니다.`),el("p","muted",`가격 부담 근거 : ${burden.reason} · 회수 위험 근거 : ${risk.reason} · 신뢰도 근거 : ${confidence.reason}`))}
function realEstatePrice(p){const o=p.offering||{},r=p.real_estate||{},cmp=realEstateComparison(p),rows=[["공모가",won(o.amount)],["취득가",won(o.acquisition)],["기준가 대비",percent(pricing(p).premium)],["위탁수익금",won(o.entrusted_benefit_payment)],["발행비용",won(o.issuance_cost)],["감정평가",(p.appraisals||[]).map(x=>`${won(x.amount)} (${x.date})`).join(" / ")||"확인 불가"]];return section("가격 구성",facts(rows),o.basis_note&&el("p","notice",o.basis_note),el("p","muted",`가격 부담 : ${cmp.verdict} · ${cmp.reason}`))}
function artPrice(p){const a=p.art_price||{},shares=a.planned_public_allocation?artShares(a):null,rows=[["공모가",won(a.offering)],["취득가",won(a.acquisition)],["발행비용",won(a.issuance_cost)],["기준가 대비",percent(pricing(p).premium)],["낙찰가",won(a.hammer)],["낙찰가 대비 공모",percent(artGap(a))]];if(shares)rows.push(["일반청약 / 공모",percent(shares.public_of_offering)],["비용 합계",shares.cost_reconciled===true?"일치":shares.cost_reconciled===false?"불일치":"확인 불가"]);const children=[facts(rows),a.chain_note&&el("p","notice",a.chain_note),a.warning&&el("p","notice stop",a.warning)];if(a.exact_work_evidence?.row_url)children.push(link("동일 작품 보고 행 원문",a.exact_work_evidence.row_url),el("p","muted",`작품 식별 신뢰도 : ${a.exact_work_evidence.identity_confidence||"확인 불가"} · lot/provenance : ${a.exact_work_evidence.provenance_or_lot||"확인 불가"}`));return section("가격 구성",...children)}
function realEstateComps(p){
 const r=p.real_estate||{},cmp=realEstateComparison(p),market=section("유사 거래",facts([["엄격 비교 건수",`${cmp.count}건 · 표본 강도 ${cmp.strength}`],["가격 부담",cmp.verdict]]),el("p","notice",`${cmp.reason} ${r.strict_rule||"엄격 비교 규칙 확인 불가"}`));
 if(p.snapshot?.rows?.length){const snap=p.snapshot,stats=broadStats(snap.rows),gap=broadGapMessage(r,snap.rows);market.append(details("저장본 넓은 범위 실거래가 · 가격 판정 미사용",el("p","muted",`${snap.mode||"저장본"} · ${snap.window||"기간 확인 불가"}`),link("RTMS 저장본 원문",snap.url),table("넓은 범위 표본",["계약일","지번 / 도로","토지 / 연면적","금액"],snap.rows.map(x=>[x.date,`${x.jibun||"확인 불가"} / ${x.road||"확인 불가"}`,`${sqm(x.land_area_m2)} / ${sqm(x.gross_area_m2)}`,won(x.amount)])),facts([["참고 중위값",`토지 ${won(stats.land_per_m2)} /㎡ · 연면적 ${won(stats.gross_per_m2)} /㎡`],["공모 대비",gap.message]])))}
 const live=r.live_analysis?.broad_comps||[];if(live.length)market.append(details("실시간 넓은 범위 비교 · 가격 판정 미사용",table("실시간 비교 표본",["계약일","토지 / 연면적","금액"],live.map(x=>[x.date||"확인 불가",`${sqm(x.land_area_m2)} / ${sqm(x.gross_area_m2)}`,won(x.amount)]))));
 if(r.live_provenance)market.append(details("실시간 RTMS 원문 정보",el("p","muted",`${kst(r.live_provenance.fetched_at)} · ${r.live_provenance.window?.from||"확인 불가"}~${r.live_provenance.window?.to||"확인 불가"}`),link("RTMS 원문",r.live_provenance.source)));
 const official=p.official_land_price,attr=p.land_attributes;if(official||attr){const landRows=[["공시지가",official?`${won(official.amount_per_m2)} /㎡`:"확인 불가"],["공시 기준",official?`${official.year||"확인 불가"} / ${kst(official.as_of)}`:"확인 불가"],["PNU",attr?.pnu||"확인 불가"],["토지 특성",attr?.characteristics?Object.values(attr.characteristics).join(" / "):"확인 불가"]];market.append(details("개별공시지가·토지 속성 · 가격 판정 미사용",facts(landRows),el("p","notice stop","개별공시지가는 토지 공시가격이며 건물 포함 공모가·실거래가와 직접 비교하거나 가격 적정성 판정에 사용하지 않습니다."),official?.source_url&&link("VWorld 개별공시지가 원문",official.source_url),attr?.characteristics_source_url&&link("VWorld 토지특성 원문",attr.characteristics_source_url),attr?.land_use_source_url&&link("VWorld 토지이용 원문",attr.land_use_source_url)))}
 const land=p.land_transactions;if(land){const query=land.query||{},rows=land.rows||[],content=details("토지 실거래가 · 가격 판정 미사용",el("p","muted",`${query.legal_dong||"법정동 확인 불가"} · 조회월 ${(query.months||[]).join("~")||"확인 불가"} · ${kst(land.fetched_at)}`),link("토지 실거래가 OpenAPI",land.source));if(rows.length)content.append(el("p","muted",`전체 ${rows.length}건 중 최대 20건 표시`),table("토지 거래 표본",["계약일","지번","면적","금액"],rows.slice(0,20).map(x=>[x.date||"확인 불가",x.jibun||"확인 불가",sqm(x.area_m2),won(x.amount)])));else content.append(el("p","muted","거래 행 : 확인 불가"));market.append(content)}
 return market
}
function artComps(p){
 const m=p.artist_market||{},a=p.art_price||{},stats=artComparableStats(p),children=[facts([["가격 부담",artEvidenceVerdict(p)],["작가 낙찰률",m.sell_through_pct!=null?`${m.sell_through_pct}%`:"확인 불가"],["KRW 비교 표본",stats.available?`${stats.count}건 · 중위값 ${won(stats.median)}`:"확인 불가"],["공모가 / 중위값",stats.available?percent(stats.offering_gap):"확인 불가"]])];
 if(m.source_note)children.push(el("p","notice",m.source_note));
 if(m.comparables?.length)children.push(details("유사 작품 원문 행",table("비교 행",["작품 / 크기","일자","경매사","금액"],m.comparables.map(x=>[`${x.work} / ${x.size}`,x.date,x.venue,`${new Intl.NumberFormat("ko-KR").format(x.amount)} ${x.currency}`])),...m.comparables.map(x=>link(`${x.work} 원문`,x.source_url))));
 if(a.independent_comparables==="insufficient")children.push(el("p","notice stop","art_price.independent_comparables=insufficient : 독립 비교 자료가 부족합니다."));
 const dart=p.dart_verification;if(dart){const receipts=dart.receipts||[],content=details("DART 원문 확인",el("p",null,dart.monetary_facts||"확인 불가"));if(receipts.length){content.append(table("원문 접수번호",["접수번호","원문 수신"],receipts.map(x=>[x.receipt_no||"확인 불가",x.original_document_received?"ZIP 원문 수신":"수신 확인 실패"])),...receipts.map(x=>link(`${x.receipt_no||"DART"} 원문`,x.source_url)))}else content.append(el("p","muted","접수번호 : 확인 불가"));children.push(content)}
 const recent=p.dart_recent_issuer_status;if(recent){const filings=recent.filings||[],content=details("최근 DART 공시",el("p","muted",`조회 시각 ${kst(recent.fetched_at)} · 최근 1년 ${filings.length}건`),recent.limitation&&el("p","notice",recent.limitation));if(filings.length){content.append(table("최근 제출 공시",["접수일","보고서"],filings.map(x=>[x.filed_at||"확인 불가",x.report_name||"확인 불가"])),...filings.map(x=>link(`${x.receipt_no||"DART"} 원문`,x.source_url)))}else content.append(el("p","muted","공시 행 : 확인 불가"));children.push(content)}
 return section("유사 거래",...children)
}
function realEstateRisk(p){const op=p.operations||{},sale=p.sale_list_check,building=p.building_verification||p.existence_check,rows=[["최근 배당 공시",op.latest_dividend_announcement?`${op.latest_dividend_announcement} · ${op.report_period_end}`:"확인 불가"],["월 임대료 / 미납",op.monthly_rent!=null?`${won(op.monthly_rent)} / ${op.rent_arrears||"확인 불가"}`:"확인 불가"],["기간 배당 / 연환산",op.dividend!=null?`${won(op.dividend)} / ${op.annualized_dividend_yield_pct??"확인 불가"}%`:"확인 불가"],["매각완료 목록",sale?`${sale.listed?"등재":"미등재"} · ${kst(sale.checked_at)}`:"확인 불가"],["독립 확인",building?.verdict||"확인 불가"]];const children=[facts(rows),op.label&&el("p","notice",op.label),building?.limitation&&el("p","notice stop",building.limitation),p.real_estate?.verdict_reason&&el("p","notice",p.real_estate.verdict_reason)];if(sale?.source_url)children.push(link("SOU 매각완료 목록 원문",sale.source_url));if(building){const buildingRows=[["주소",building.address||"확인 불가"],["대지 / 연면적",`${sqm(building.site_area_m2)} / ${sqm(building.gross_floor_area_m2)}`],["사용승인 / 용도",`${building.completion_date||"확인 불가"} / ${building.use||"확인 불가"}`],["범위 일치",building.scope_complete===true?"확인":building.scope_complete===false?"미확인":"확인 불가"]],conflicts=building.source_conflicts||[];children.push(details("건축물·권리 확인 범위",el("p",null,building.verified_facts||"확인 불가"),facts(buildingRows),...conflicts.map(x=>el("p","notice stop",`원문 차이 : ${x}`)),link("건축물대장 공식 API",building.source||building.source_url)))}return section("배당·유동성·회수 위험",...children)}
function artRisk(p){const m=p.artist_market||{},platform=p.platform_check,completion=p.completion_check||p.disposition_check,completed=lifecycleState(p)==="COMPLETED",rows=[["배당",p.dividend?.amount!=null?won(p.dividend.amount):"확인 불가"],["유동성",p.liquidity?.verdict||"확인 불가"],["작가 시장 기간",m.period||m.year||"확인 불가"],["플랫폼 상태",platform?`${platform.code} · ${kst(platform.checked_at)}`:"확인 불가"],["완료 확인",completed?"확인":"확인 불가"],["완료 확인 기준일",completed?kst(completion?.checked_at):"확인 불가"],["회수 위험",recoveryRisk(p).value]],children=[facts(rows),m.source_note&&el("p","notice",m.source_note),platform?.limitation&&el("p","notice stop",platform.limitation),m.different_work&&el("p","notice stop",`다른 작품 거래 : ${m.different_work.work} · 동일 작품 비교에 사용하지 않음`)];if(completed)children.push(link("완료 확인 원문",completion?.source_url));return section("배당·유동성·회수 위험",...children)}
function issuerHistory(p){const issuer=S.issuers.find(i=>i.name===p.issuer);if(!issuer)return section("사업자 이력",el("p","muted","확인 불가"));const links=el("div","links");(issuer.sources||[]).forEach(s=>links.append(link(`${s.label} · ${kst(s.as_of)}`,s.url)));return section("사업자 이력",table("사업자 원문 이력",["기준일","구분","확인된 사실"],(issuer.records||[]).map(x=>[x.date,x.type,x.fact])),links)}
function sourceEvidence(p){const links=el("div","links"),names={sou:"SOU 상품 원문",commercial_rtms:"상업·업무용 실거래가",land_rtms:"토지 실거래가",building:"건축물대장",vworld:"VWorld 토지정보",dart:"OpenDART",pipeline:"상품 파이프라인"},completion=p.completion_check||p.disposition_check;(p.sources||[]).forEach(s=>links.append(link(`${s.label} · ${kst(s.as_of)}`,s.url)));if(lifecycleState(p)==="COMPLETED")links.append(link("완료 확인 원문",completion?.source_url));const scoped=S.apiStatus?.products?.[p.id]||{},global=p.category==="미술품"?(S.apiStatus?.global||{}):{},apiRows=Object.entries({...scoped,...global});return section("원문 근거",sourceBadges(p),links,details("검색·API·기술 정보",apiRows.length?table("출처별 API 상태",["출처","상태"],apiRows.map(([key,value])=>[names[key]||key,`${value.message||"확인 불가"} · ${kst(value.as_of)}`])):el("p","muted","이 상품의 별도 API 상태 저장본이 없습니다.")))}
function renderDetail(focus=false){const root=$("detail"),p=S.products.find(x=>x.id===S.selected)||filteredProducts()[0];root.replaceChildren();root.setAttribute("role","region");root.setAttribute("tabindex","-1");if(!p){root.setAttribute("aria-label","상품 상세");root.append(el("p","empty","필터 조건에 맞는 상품이 없습니다."));return}S.selected=p.id;root.setAttribute("aria-label",`${p.name} 상세`);const heading=el("div","detail-heading");heading.append(el("h2",null,p.name),sourceBadges(p));root.append(heading,commonSnapshot(p),p.category==="부동산"?realEstatePrice(p):artPrice(p),p.category==="부동산"?realEstateComps(p):artComps(p),p.category==="부동산"?realEstateRisk(p):artRisk(p),issuerHistory(p),sourceEvidence(p));if(focus)root.focus({preventScroll:true})}
function render(){const visible=filteredProducts();if(!visible.some(p=>p.id===S.selected))S.selected=visible[0]?.id||null;renderFilters();renderCards();renderCompare();renderDetail()}

$("search-input").addEventListener("input",event=>{S.query=event.target.value;S.selected=null;render()});
try{const catalog=await loadCatalog();S.products=catalog.products;S.issuers=catalog.issuers;S.apiStatus=catalog.api_status||{};$("load-state").textContent=catalog.live_status?.message||"저장본 기준";render()}catch{S.loadError=true;$("load-state").textContent="자료를 불러오지 못했습니다.";render()}
