export const KRW=new Intl.NumberFormat("ko-KR",{style:"currency",currency:"KRW",maximumFractionDigits:0});
export const won=v=>Number.isFinite(v)?KRW.format(v):"확인 불가";
export const percent=v=>{if(v==null||!Number.isFinite(v))return "확인 불가";const scaled=v*100,rounded=Math.sign(scaled)*Math.floor(Math.abs(scaled)*100+.500000001)/100;return `${rounded.toFixed(2)}%`};

const kstMidnight=date=>{const kst=new Date(date.getTime()+32400000);return new Date(Date.UTC(kst.getUTCFullYear(),kst.getUTCMonth(),kst.getUTCDate())-32400000)};
const calendarDate=(year,month,day)=>{const probe=new Date(Date.UTC(year,month-1,day));return probe.getUTCFullYear()===year&&probe.getUTCMonth()===month-1&&probe.getUTCDate()===day?kstMidnight(probe):null};
const instantValue=value=>{if(!value)return null;if(value instanceof Date)return Number.isNaN(value.getTime())?null:value;const text=String(value),day=/^(\d{4})-(\d{2})-(\d{2})$/.exec(text);if(day)return calendarDate(...day.slice(1).map(Number));const timestamp=/^(\d{4})-(\d{2})-(\d{2})T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:?\d{2})$/.exec(text);if(!timestamp||!calendarDate(...timestamp.slice(1,4).map(Number)))return null;const parsed=new Date(text);return Number.isNaN(parsed.getTime())?null:parsed};
const dateValue=value=>{const instant=instantValue(value);return instant?kstMidnight(instant):null};
export function sourceExpired(asOf,referenceAsOf){const source=dateValue(asOf),reference=dateValue(referenceAsOf);return !source||!reference?null:(reference-source)/86400000>180}
export function pricing(product){const realEstate=product?.category==="부동산",offering=realEstate?product?.offering?.amount:product?.art_price?.offering,base=realEstate?product?.offering?.acquisition:product?.art_price?.acquisition;return {offering:Number.isFinite(offering)?offering:null,base:Number.isFinite(base)&&base>0?base:null,premium:Number.isFinite(offering)&&Number.isFinite(base)&&base>0?offering/base-1:null,base_field:realEstate?"offering.acquisition":"art_price.acquisition"}}
const statusOnly=p=>String(p?.status||"");
const escapeRegExp=value=>String(value).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const hasStatusPhrase=(status,phrase)=>new RegExp(`(^|[·/ ])${escapeRegExp(phrase)}($|[·/ ])`).test(String(status||""));
const hasAnyStatusPhrase=(status,phrases)=>phrases.some(phrase=>hasStatusPhrase(status,phrase));
const artCompletionNegatives=["처분 공시 미발견","미처분 독립 확인 안 됨"];
const recoveryUnknownPhrases=["매각완료 목록 미등재","처분 공시 미발견","현재 상태 재확인 필요","미처분 독립 확인 안 됨"];
const validHttp=value=>{try{return ["http:","https:"].includes(new URL(value).protocol)}catch{return false}};
const completionCurrent=({checked_at},product,now)=>{const checked=instantValue(checked_at),current=instantValue(now),asOf=dateValue(product?.as_of),checkedDay=dateValue(checked_at);return !!checked&&!!current&&!!checkedDay&&checked<=current&&(!asOf||checkedDay<=asOf)};
const hasVerifiedCompletion=(check,product,now)=>check?.confirmed===true&&validHttp(check.source_url)&&completionCurrent(check,product,now);
const hasVerifiedSale=(check,product,now)=>check?.listed===true&&validHttp(check.source_url)&&completionCurrent(check,product,now);
export function lifecycleState(product,now=new Date()){const status=statusOnly(product),detail=String(product?.status_detail||""),negative=recoveryUnknownPhrases.some(phrase=>status.includes(phrase)||detail.includes(phrase));if(!status.trim())return "UNCONFIRMED";if(hasStatusPhrase(status,"공모 예정"))return "UPCOMING";if(hasStatusPhrase(status,"청약 중"))return "SUBSCRIPTION";if(product?.category==="부동산"){const completed=hasAnyStatusPhrase(status,["매각 완료","상환 완료"]);if(completed&&hasVerifiedSale(product?.sale_list_check,product,now)&&!negative)return "COMPLETED";return hasStatusPhrase(status,"운용 중")?"OPERATING":"OUTSIDE_FILTER"}const completed=hasAnyStatusPhrase(status,["처분 완료","상환 완료"]),check=product?.completion_check||product?.disposition_check;if(completed&&hasVerifiedCompletion(check,product,now)&&!hasAnyStatusPhrase(status,artCompletionNegatives)&&!negative)return "COMPLETED";return hasStatusPhrase(status,"운용 중")?"OPERATING":"OUTSIDE_FILTER"}
export function lifecycleLabel(state){return ({UPCOMING:"공모 예정",SUBSCRIPTION:"청약 중",OPERATING:"운용 중",COMPLETED:"매각·상환 완료",OUTSIDE_FILTER:"전체 상태에서만 표시",UNCONFIRMED:"상태 확인 불가"})[state]||"상태 확인 불가"}
export function recoveryRisk(product,now=new Date()){const lifecycle=lifecycleState(product,now),status=statusOnly(product),detail=String(product?.status_detail||""),hasRecoveryUnknown=value=>recoveryUnknownPhrases.some(phrase=>String(value).includes(phrase));if(lifecycle==="COMPLETED")return {value:"회수 완료 확인",reason:"회수 완료 상태가 확인됨"};if(product?.status_code==="TRADING_STOPPED")return {value:"회수 경로 제한",reason:"거래 중단 상태가 확인됨"};if(product?.sale_list_check?.listed===false)return {value:"확인 필요",reason:"매각완료 목록 미등재"};if(hasRecoveryUnknown(status)||hasRecoveryUnknown(detail))return {value:"확인 필요",reason:"현재 자료에서 회수 상태를 확인하지 못함"};return {value:"확인 불가",reason:"현재 자료에서 회수 상태를 확인하지 못함"}}
export function evidenceConfidence(product,now=new Date()){const reference=product?.as_of,sources=Array.isArray(product?.sources)?product.sources:[],current=dateValue(now),ref=dateValue(reference);if(!sources.length)return {value:"확인 불가",reason:"원문 출처 없음"};if(!current||!ref)return {value:"확인 불가",reason:"상품 기준일 없음"};if(!sources.every(s=>String(s?.label||"").trim()))return {value:"확인 불가",reason:"원문 출처 이름 없음"};if(!sources.every(s=>validHttp(s?.url)))return {value:"확인 불가",reason:"원문 출처 URL 확인 불가"};if(!sources.every(s=>dateValue(s?.as_of)))return {value:"확인 불가",reason:"원문 기준일 없음"};if(ref>current||sources.some(s=>dateValue(s.as_of)>current))return {value:"확인 불가",reason:"상품 또는 원문 기준일이 현재 조회일 이후"};if(sourceExpired(reference,now)===true)return {value:"현재성 확인 필요",reason:"현재 조회일 대비 상품 기준일 180일 초과"};if(sources.some(s=>sourceExpired(s.as_of,reference)===true))return {value:"현재성 확인 필요",reason:"상품 기준일 대비 원문 기준일 180일 초과"};if(product?.category==="부동산"){const comparison=realEstateComparison(product);return comparison.code==="INSUFFICIENT"?{value:"제한적",reason:"엄격 비교 근거가 가격 판정에 충분하지 않음"}:{value:"보통",reason:"엄격 비교 표본 5건 이상"}}const art=product?.art_price||{},exact=art.exact_work_evidence||{};if(art.independent_comparables==="insufficient")return {value:"제한적",reason:"독립 비교자료 부족"};if(exact.identity_confidence==="높음"&&exact.reported===true&&validHttp(exact.row_url))return {value:"보통",reason:"동일 작품 식별 신뢰도 높음"};return {value:"제한적",reason:"원문 연결 근거만 존재"}}

export function searchProducts(products,q){const x=String(q||"").trim().toLowerCase();if(!x)return products;return products.filter(p=>{const values=[p?.name,p?.issuer,p?.asset?.address,p?.asset?.artist,p?.asset?.title,...(p?.dart_verification?.receipts||[]).flatMap(r=>[r?.receipt_no]),...(p?.dart_recent_issuer_status?.filings||[]).flatMap(f=>[f?.receipt_no,f?.report_name]),...(p?.sources||[]).flatMap(s=>[s?.label,s?.url])];return values.some(value=>String(value||"").toLowerCase().includes(x))})}
export function selectionAfterSearch(products,query,current){const found=searchProducts(products,query);return found.find(x=>x.id===current?.id)||found[0]||null}

const med=a=>{if(!a.length)return null;const v=[...a].sort((x,y)=>x-y),n=v.length;return n%2?v[(n-1)/2]:(v[n/2-1]+v[n/2])/2};
const positive=v=>Number.isFinite(v)&&v>0;
export function broadStats(rows){const usable=(rows||[]).filter(r=>r&&positive(r.amount)&&positive(r.land_area_m2)&&positive(r.gross_area_m2)),land=usable.map(r=>r.amount/r.land_area_m2),gross=usable.map(r=>r.amount/r.gross_area_m2);const lm=med(land),gm=med(gross);return {land_per_m2:lm,gross_per_m2:gm,land_mad:med(land.map(x=>Math.abs(x-lm))),gross_mad:med(gross.map(x=>Math.abs(x-gm)))}}
export function broadGapMessage(realEstate,rows){const s=broadStats(rows),offering=realEstate?.offering_units||{};if(!positive(s.land_per_m2)||!positive(s.gross_per_m2)||!positive(offering.land_per_m2)||!positive(offering.gross_per_m2))return {land:null,gross:null,message:"비교 단가 확인 불가"};const land=offering.land_per_m2/s.land_per_m2-1,gross=offering.gross_per_m2/s.gross_per_m2-1,signal=(land>=.2)!==(gross>=.2)?"기준별 20% 경고 신호가 엇갈립니다.":"두 기준의 20% 경고 신호가 같습니다.";return {land,gross,message:`토지 ${percent(land)}, 연면적 ${percent(gross)}. ${signal}`}}
export function realEstateComparison(product){const r=product.real_estate||{},strict=r.live_analysis?.strict_comps||r.strict_comps||[],n=strict.length,insufficient=(reason="엄격 조건 비교가 0~4건입니다.")=>({code:"INSUFFICIENT",count:n,strength:"보류",verdict:"자료 부족·가격 적정성 판정 보류",reason});if(n<5)return insufficient();const og=r.offering_units||{},rowsValid=strict.every(row=>positive(row?.land_per_m2)&&positive(row?.gross_per_m2));if(!positive(og.land_per_m2)||!positive(og.gross_per_m2)||!rowsValid)return insufficient("비교 단가 또는 공모 단가 확인 불가.");const land=med(strict.map(x=>x.land_per_m2)),gross=med(strict.map(x=>x.gross_per_m2));if(!positive(land)||!positive(gross))return insufficient("비교 단가 또는 공모 단가 확인 불가.");const gaps={land:(og.land_per_m2/land-1)*100,gross:(og.gross_per_m2/gross-1)*100},spread=Math.abs(gaps.land-gaps.gross),high=gaps.land>=20&&gaps.gross>=20,low=gaps.land<=-20&&gaps.gross<=-20,mismatch=spread>=20||((gaps.land>=20)!==(gaps.gross>=20))||((gaps.land<=-20)!==(gaps.gross<=-20))||(gaps.land*gaps.gross<0),code=mismatch?"INSUFFICIENT":high?"PRICE_CAUTION":low?"BELOW_RANGE":"COMPARABLE",verdict=code==="INSUFFICIENT"?"자료 부족·가격 적정성 판정 보류":code==="PRICE_CAUTION"?"가격 주의":code==="BELOW_RANGE"?"낮은 범위":"비교 범위";return {code,count:n,strength:n<10?"낮음":"중간",verdict,gaps,reason:mismatch?"토지·연면적 비교 신호가 엇갈리거나 차이가 큽니다.":"엄격 비교 표본만 사용했습니다."}}
export function artEvidenceAssessment(p){if(!dateValue(p?.as_of))return {code:"UNKNOWN",label:"확인 불가"};const a=p?.art_price||{};if(a.independent_comparables==="insufficient")return {code:"INSUFFICIENT",label:"독립 비교자료 부족 · 가격 적정성 판정 보류"};const exact=a.exact_work_evidence?.reported&&a.exact_work_evidence?.row_url,weakIdentity=a.exact_work_evidence?.identity_confidence!=="높음";if(exact&&weakIdentity)return {code:"PRICE_CAUTION",label:"가격 주의 신호·근거 보강 필요"};if(a.acquisition!=null&&a.issuance_cost!=null&&a.offering===a.acquisition+a.issuance_cost)return {code:"REVIEW_NEEDED",label:"비용 연결 확인 · 가격 적정성은 별도 확인 필요"};return {code:"INSUFFICIENT",label:"자료 부족·판정 보류"}}
export const artEvidenceVerdict=p=>artEvidenceAssessment(p).label;
export function priceBurden(product){const assessment=product?.category==="부동산"?realEstateComparison(product):artEvidenceAssessment(product),value=({PRICE_CAUTION:"가격 주의",COMPARABLE:"비교 범위",BELOW_RANGE:"낮은 범위",UNKNOWN:"확인 불가",INSUFFICIENT:"판정 보류",REVIEW_NEEDED:"판정 보류"})[assessment.code]||"확인 불가";return {value,reason:assessment.verdict||assessment.label}}
export const artGap=a=>a?.hammer!=null&&a?.offering!=null?(a.offering-a.hammer)/a.hammer:null;
export function artComparableStats(product){const a=product.art_price||{},all=product.artist_market?.comparables;if(!Array.isArray(all))return {available:false,count:null,median:null,offering_gap:null,acquisition_gap:null,excluded_currency_count:null};const rows=all.filter(x=>x.currency==="KRW"&&Number.isFinite(x.amount)),values=rows.map(x=>x.amount),mid=med(values);return {available:true,count:rows.length,median:mid,offering_gap:mid&&a.offering?(a.offering/mid-1):null,acquisition_gap:mid&&a.acquisition?(a.acquisition/mid-1):null,excluded_currency_count:all.length-rows.length}}
export function artShares(a={}){const valid=v=>Number.isFinite(v)&&v>0,offering=valid(a.offering)?a.offering:null,publicSubscription=valid(a.public_subscription)?a.public_subscription:null,planned=valid(a.planned_public_allocation)?a.planned_public_allocation:null,issuer=valid(a.issuer_take_up)?a.issuer_take_up:null,costs=valid(a.acquisition)&&Number.isFinite(a.issuance_cost)?a.acquisition+a.issuance_cost:null;return {public_of_offering:offering&&publicSubscription?publicSubscription/offering:null,public_of_planned:planned&&publicSubscription?publicSubscription/planned:null,issuer_of_offering:offering&&issuer?issuer/offering:null,cost_reconciled:costs!=null&&offering!=null?costs===offering:null}}
