import Link from "next/link";
import { NaturalLanguageSearch } from "@/components/art/natural-search";
import { EmptyState, PageContainer, ProductCard } from "@/components/art/ui";
import type { OfferingStatus, ParsedSearchQuery, Verdict } from "@/lib/art/types";
import { parseDemoSearchQuery, searchConditionEntries } from "@/lib/art/search";
import { filterProducts, productRepository, statusLabels, verdictLabels } from "@/lib/repositories/art-repositories";
type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};const str=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??"":v??"";
export default async function ProductsPage({searchParams}:Props){const raw=await searchParams;const q=str(raw.q);const fromQuery=parseDemoSearchQuery(q);const parsed:ParsedSearchQuery={...fromQuery};const split=(key:string)=>str(raw[key]).split(",").filter(Boolean);const statuses=split("status") as OfferingStatus[];const verdicts=split("verdict") as Verdict[];if(statuses.length)parsed.offeringStatus=statuses;if(verdicts.length)parsed.verdict=verdicts;if(raw.premiumMin)parsed.premiumMin=Number(str(raw.premiumMin));if(raw.premiumMax)parsed.premiumMax=Number(str(raw.premiumMax));if(raw.auctionVolumeMin)parsed.auctionVolumeMin=Number(str(raw.auctionVolumeMin));if(raw.sellThroughRateMin)parsed.sellThroughRateMin=Number(str(raw.sellThroughRateMin));if(str(raw.delayed)==="1")parsed.delayedExitOnly=true;if(raw.sort)parsed.sort=str(raw.sort);if(raw.keyword)parsed.keyword=str(raw.keyword);const results=filterProducts(productRepository.getList(),parsed);const chips=searchConditionEntries(parsed);return <main id="main-content" className="listing-page"><PageContainer><header className="page-title"><p className="section-kicker">PRODUCTS</p><h1>청약 상품 분석</h1><p>자연어로 찾거나 상태·AI 판단·가격 조건을 조합하세요. 검색 상태는 URL에 유지됩니다.</p></header><NaturalLanguageSearch defaultValue={q} compact/>
<div className="condition-row" aria-label="AI가 인식한 조건">{chips.length?<>{chips.map((chip,i)=><span className="condition-chip" key={`${chip.key}-${i}`}>{chip.label}<Link aria-label={`${chip.label} 조건 제거`} href="/products">×</Link></span>)}<Link className="reset-link" href="/products">필터 초기화</Link></>:<span>AI가 인식한 조건이 여기에 표시됩니다.</span>}</div>
<details className="mobile-filter"><summary>필터 열기</summary><div><strong>청약 상태</strong>{Object.entries(statusLabels).map(([value,label])=><Link key={value} href={`/products?status=${value}`}>{label}</Link>)}</div><div><strong>AI 판단</strong>{Object.entries(verdictLabels).map(([value,label])=><Link key={value} href={`/products?verdict=${value}`}>{label}</Link>)}</div></details><div className="listing-layout"><aside className="filter-panel"><h2>필터</h2><div><strong>청약 상태</strong>{Object.entries(statusLabels).map(([value,label])=><Link key={value} className={parsed.offeringStatus?.includes(value as OfferingStatus)?"selected":""} href={`/products?status=${value}`}>{label}</Link>)}</div><div><strong>AI 최종 판단</strong>{Object.entries(verdictLabels).map(([value,label])=><Link key={value} className={parsed.verdict?.includes(value as Verdict)?"selected":""} href={`/products?verdict=${value}`}>{label}</Link>)}</div><div><strong>공모가 차이율</strong><Link href="/products?premiumMax=15">15% 이하</Link><Link href="/products?premiumMin=15">15% 이상</Link></div></aside><section className="listing-results" aria-live="polite"><div className="results-toolbar"><strong>{results.length}개 분석 상품</strong><div className="sort-links"><span>정렬</span><Link href="/products?sort=deadline">청약 마감 임박순</Link><Link href="/products?sort=verdict">AI 판단순</Link><Link href="/products?sort=premium_desc">공모가 차이 높은 순</Link><Link href="/products?sort=auction_volume_desc">작가 거래량 높은 순</Link></div></div>{results.length?<div className="product-grid-art">{results.map(p=><ProductCard key={p.offering.id} product={p}/>)}</div>:<EmptyState/>}</section></div></PageContainer></main>}
